
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BotEmpresa` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BotEmpresa
 * 
 */
export type BotEmpresaModel = runtime.Types.Result.DefaultSelection<Prisma.$BotEmpresaPayload>

export type AggregateBotEmpresa = {
  _count: BotEmpresaCountAggregateOutputType | null
  _min: BotEmpresaMinAggregateOutputType | null
  _max: BotEmpresaMaxAggregateOutputType | null
}

export type BotEmpresaMinAggregateOutputType = {
  id: string | null
  botId: string | null
  empresaId: string | null
  departamentoId: string | null
  data_contrato: Date | null
  status: $Enums.ACCOUNT_STATUS | null
}

export type BotEmpresaMaxAggregateOutputType = {
  id: string | null
  botId: string | null
  empresaId: string | null
  departamentoId: string | null
  data_contrato: Date | null
  status: $Enums.ACCOUNT_STATUS | null
}

export type BotEmpresaCountAggregateOutputType = {
  id: number
  botId: number
  empresaId: number
  departamentoId: number
  data_contrato: number
  status: number
  _all: number
}


export type BotEmpresaMinAggregateInputType = {
  id?: true
  botId?: true
  empresaId?: true
  departamentoId?: true
  data_contrato?: true
  status?: true
}

export type BotEmpresaMaxAggregateInputType = {
  id?: true
  botId?: true
  empresaId?: true
  departamentoId?: true
  data_contrato?: true
  status?: true
}

export type BotEmpresaCountAggregateInputType = {
  id?: true
  botId?: true
  empresaId?: true
  departamentoId?: true
  data_contrato?: true
  status?: true
  _all?: true
}

export type BotEmpresaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BotEmpresa to aggregate.
   */
  where?: Prisma.BotEmpresaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BotEmpresas to fetch.
   */
  orderBy?: Prisma.BotEmpresaOrderByWithRelationInput | Prisma.BotEmpresaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BotEmpresaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BotEmpresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BotEmpresas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BotEmpresas
  **/
  _count?: true | BotEmpresaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BotEmpresaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BotEmpresaMaxAggregateInputType
}

export type GetBotEmpresaAggregateType<T extends BotEmpresaAggregateArgs> = {
      [P in keyof T & keyof AggregateBotEmpresa]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBotEmpresa[P]>
    : Prisma.GetScalarType<T[P], AggregateBotEmpresa[P]>
}




export type BotEmpresaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BotEmpresaWhereInput
  orderBy?: Prisma.BotEmpresaOrderByWithAggregationInput | Prisma.BotEmpresaOrderByWithAggregationInput[]
  by: Prisma.BotEmpresaScalarFieldEnum[] | Prisma.BotEmpresaScalarFieldEnum
  having?: Prisma.BotEmpresaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BotEmpresaCountAggregateInputType | true
  _min?: BotEmpresaMinAggregateInputType
  _max?: BotEmpresaMaxAggregateInputType
}

export type BotEmpresaGroupByOutputType = {
  id: string
  botId: string
  empresaId: string
  departamentoId: string
  data_contrato: Date
  status: $Enums.ACCOUNT_STATUS
  _count: BotEmpresaCountAggregateOutputType | null
  _min: BotEmpresaMinAggregateOutputType | null
  _max: BotEmpresaMaxAggregateOutputType | null
}

type GetBotEmpresaGroupByPayload<T extends BotEmpresaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BotEmpresaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BotEmpresaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BotEmpresaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BotEmpresaGroupByOutputType[P]>
      }
    >
  >



export type BotEmpresaWhereInput = {
  AND?: Prisma.BotEmpresaWhereInput | Prisma.BotEmpresaWhereInput[]
  OR?: Prisma.BotEmpresaWhereInput[]
  NOT?: Prisma.BotEmpresaWhereInput | Prisma.BotEmpresaWhereInput[]
  id?: Prisma.StringFilter<"BotEmpresa"> | string
  botId?: Prisma.StringFilter<"BotEmpresa"> | string
  empresaId?: Prisma.StringFilter<"BotEmpresa"> | string
  departamentoId?: Prisma.StringFilter<"BotEmpresa"> | string
  data_contrato?: Prisma.DateTimeFilter<"BotEmpresa"> | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFilter<"BotEmpresa"> | $Enums.ACCOUNT_STATUS
  bot?: Prisma.XOR<Prisma.BotScalarRelationFilter, Prisma.BotWhereInput>
  empresa?: Prisma.XOR<Prisma.EmpresaScalarRelationFilter, Prisma.EmpresaWhereInput>
  departamento?: Prisma.XOR<Prisma.DepartamentoScalarRelationFilter, Prisma.DepartamentoWhereInput>
  folhas_pag?: Prisma.FolhaBotListRelationFilter
}

export type BotEmpresaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  botId?: Prisma.SortOrder
  empresaId?: Prisma.SortOrder
  departamentoId?: Prisma.SortOrder
  data_contrato?: Prisma.SortOrder
  status?: Prisma.SortOrder
  bot?: Prisma.BotOrderByWithRelationInput
  empresa?: Prisma.EmpresaOrderByWithRelationInput
  departamento?: Prisma.DepartamentoOrderByWithRelationInput
  folhas_pag?: Prisma.FolhaBotOrderByRelationAggregateInput
}

export type BotEmpresaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BotEmpresaWhereInput | Prisma.BotEmpresaWhereInput[]
  OR?: Prisma.BotEmpresaWhereInput[]
  NOT?: Prisma.BotEmpresaWhereInput | Prisma.BotEmpresaWhereInput[]
  botId?: Prisma.StringFilter<"BotEmpresa"> | string
  empresaId?: Prisma.StringFilter<"BotEmpresa"> | string
  departamentoId?: Prisma.StringFilter<"BotEmpresa"> | string
  data_contrato?: Prisma.DateTimeFilter<"BotEmpresa"> | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFilter<"BotEmpresa"> | $Enums.ACCOUNT_STATUS
  bot?: Prisma.XOR<Prisma.BotScalarRelationFilter, Prisma.BotWhereInput>
  empresa?: Prisma.XOR<Prisma.EmpresaScalarRelationFilter, Prisma.EmpresaWhereInput>
  departamento?: Prisma.XOR<Prisma.DepartamentoScalarRelationFilter, Prisma.DepartamentoWhereInput>
  folhas_pag?: Prisma.FolhaBotListRelationFilter
}, "id">

export type BotEmpresaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  botId?: Prisma.SortOrder
  empresaId?: Prisma.SortOrder
  departamentoId?: Prisma.SortOrder
  data_contrato?: Prisma.SortOrder
  status?: Prisma.SortOrder
  _count?: Prisma.BotEmpresaCountOrderByAggregateInput
  _max?: Prisma.BotEmpresaMaxOrderByAggregateInput
  _min?: Prisma.BotEmpresaMinOrderByAggregateInput
}

export type BotEmpresaScalarWhereWithAggregatesInput = {
  AND?: Prisma.BotEmpresaScalarWhereWithAggregatesInput | Prisma.BotEmpresaScalarWhereWithAggregatesInput[]
  OR?: Prisma.BotEmpresaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BotEmpresaScalarWhereWithAggregatesInput | Prisma.BotEmpresaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BotEmpresa"> | string
  botId?: Prisma.StringWithAggregatesFilter<"BotEmpresa"> | string
  empresaId?: Prisma.StringWithAggregatesFilter<"BotEmpresa"> | string
  departamentoId?: Prisma.StringWithAggregatesFilter<"BotEmpresa"> | string
  data_contrato?: Prisma.DateTimeWithAggregatesFilter<"BotEmpresa"> | Date | string
  status?: Prisma.EnumACCOUNT_STATUSWithAggregatesFilter<"BotEmpresa"> | $Enums.ACCOUNT_STATUS
}

export type BotEmpresaCreateInput = {
  id?: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
  bot: Prisma.BotCreateNestedOneWithoutContratosInput
  empresa: Prisma.EmpresaCreateNestedOneWithoutBots_alocadosInput
  departamento: Prisma.DepartamentoCreateNestedOneWithoutBotsInput
  folhas_pag?: Prisma.FolhaBotCreateNestedManyWithoutBotEmpresaInput
}

export type BotEmpresaUncheckedCreateInput = {
  id?: string
  botId: string
  empresaId: string
  departamentoId: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
  folhas_pag?: Prisma.FolhaBotUncheckedCreateNestedManyWithoutBotEmpresaInput
}

export type BotEmpresaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
  bot?: Prisma.BotUpdateOneRequiredWithoutContratosNestedInput
  empresa?: Prisma.EmpresaUpdateOneRequiredWithoutBots_alocadosNestedInput
  departamento?: Prisma.DepartamentoUpdateOneRequiredWithoutBotsNestedInput
  folhas_pag?: Prisma.FolhaBotUpdateManyWithoutBotEmpresaNestedInput
}

export type BotEmpresaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  botId?: Prisma.StringFieldUpdateOperationsInput | string
  empresaId?: Prisma.StringFieldUpdateOperationsInput | string
  departamentoId?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
  folhas_pag?: Prisma.FolhaBotUncheckedUpdateManyWithoutBotEmpresaNestedInput
}

export type BotEmpresaCreateManyInput = {
  id?: string
  botId: string
  empresaId: string
  departamentoId: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
}

export type BotEmpresaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
}

export type BotEmpresaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  botId?: Prisma.StringFieldUpdateOperationsInput | string
  empresaId?: Prisma.StringFieldUpdateOperationsInput | string
  departamentoId?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
}

export type BotEmpresaListRelationFilter = {
  every?: Prisma.BotEmpresaWhereInput
  some?: Prisma.BotEmpresaWhereInput
  none?: Prisma.BotEmpresaWhereInput
}

export type BotEmpresaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BotEmpresaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  botId?: Prisma.SortOrder
  empresaId?: Prisma.SortOrder
  departamentoId?: Prisma.SortOrder
  data_contrato?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type BotEmpresaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  botId?: Prisma.SortOrder
  empresaId?: Prisma.SortOrder
  departamentoId?: Prisma.SortOrder
  data_contrato?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type BotEmpresaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  botId?: Prisma.SortOrder
  empresaId?: Prisma.SortOrder
  departamentoId?: Prisma.SortOrder
  data_contrato?: Prisma.SortOrder
  status?: Prisma.SortOrder
}

export type BotEmpresaScalarRelationFilter = {
  is?: Prisma.BotEmpresaWhereInput
  isNot?: Prisma.BotEmpresaWhereInput
}

export type BotEmpresaCreateNestedManyWithoutEmpresaInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutEmpresaInput, Prisma.BotEmpresaUncheckedCreateWithoutEmpresaInput> | Prisma.BotEmpresaCreateWithoutEmpresaInput[] | Prisma.BotEmpresaUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutEmpresaInput | Prisma.BotEmpresaCreateOrConnectWithoutEmpresaInput[]
  createMany?: Prisma.BotEmpresaCreateManyEmpresaInputEnvelope
  connect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
}

export type BotEmpresaUncheckedCreateNestedManyWithoutEmpresaInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutEmpresaInput, Prisma.BotEmpresaUncheckedCreateWithoutEmpresaInput> | Prisma.BotEmpresaCreateWithoutEmpresaInput[] | Prisma.BotEmpresaUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutEmpresaInput | Prisma.BotEmpresaCreateOrConnectWithoutEmpresaInput[]
  createMany?: Prisma.BotEmpresaCreateManyEmpresaInputEnvelope
  connect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
}

export type BotEmpresaUpdateManyWithoutEmpresaNestedInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutEmpresaInput, Prisma.BotEmpresaUncheckedCreateWithoutEmpresaInput> | Prisma.BotEmpresaCreateWithoutEmpresaInput[] | Prisma.BotEmpresaUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutEmpresaInput | Prisma.BotEmpresaCreateOrConnectWithoutEmpresaInput[]
  upsert?: Prisma.BotEmpresaUpsertWithWhereUniqueWithoutEmpresaInput | Prisma.BotEmpresaUpsertWithWhereUniqueWithoutEmpresaInput[]
  createMany?: Prisma.BotEmpresaCreateManyEmpresaInputEnvelope
  set?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  disconnect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  delete?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  connect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  update?: Prisma.BotEmpresaUpdateWithWhereUniqueWithoutEmpresaInput | Prisma.BotEmpresaUpdateWithWhereUniqueWithoutEmpresaInput[]
  updateMany?: Prisma.BotEmpresaUpdateManyWithWhereWithoutEmpresaInput | Prisma.BotEmpresaUpdateManyWithWhereWithoutEmpresaInput[]
  deleteMany?: Prisma.BotEmpresaScalarWhereInput | Prisma.BotEmpresaScalarWhereInput[]
}

export type BotEmpresaUncheckedUpdateManyWithoutEmpresaNestedInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutEmpresaInput, Prisma.BotEmpresaUncheckedCreateWithoutEmpresaInput> | Prisma.BotEmpresaCreateWithoutEmpresaInput[] | Prisma.BotEmpresaUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutEmpresaInput | Prisma.BotEmpresaCreateOrConnectWithoutEmpresaInput[]
  upsert?: Prisma.BotEmpresaUpsertWithWhereUniqueWithoutEmpresaInput | Prisma.BotEmpresaUpsertWithWhereUniqueWithoutEmpresaInput[]
  createMany?: Prisma.BotEmpresaCreateManyEmpresaInputEnvelope
  set?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  disconnect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  delete?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  connect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  update?: Prisma.BotEmpresaUpdateWithWhereUniqueWithoutEmpresaInput | Prisma.BotEmpresaUpdateWithWhereUniqueWithoutEmpresaInput[]
  updateMany?: Prisma.BotEmpresaUpdateManyWithWhereWithoutEmpresaInput | Prisma.BotEmpresaUpdateManyWithWhereWithoutEmpresaInput[]
  deleteMany?: Prisma.BotEmpresaScalarWhereInput | Prisma.BotEmpresaScalarWhereInput[]
}

export type BotEmpresaCreateNestedManyWithoutDepartamentoInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutDepartamentoInput, Prisma.BotEmpresaUncheckedCreateWithoutDepartamentoInput> | Prisma.BotEmpresaCreateWithoutDepartamentoInput[] | Prisma.BotEmpresaUncheckedCreateWithoutDepartamentoInput[]
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutDepartamentoInput | Prisma.BotEmpresaCreateOrConnectWithoutDepartamentoInput[]
  createMany?: Prisma.BotEmpresaCreateManyDepartamentoInputEnvelope
  connect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
}

export type BotEmpresaUncheckedCreateNestedManyWithoutDepartamentoInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutDepartamentoInput, Prisma.BotEmpresaUncheckedCreateWithoutDepartamentoInput> | Prisma.BotEmpresaCreateWithoutDepartamentoInput[] | Prisma.BotEmpresaUncheckedCreateWithoutDepartamentoInput[]
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutDepartamentoInput | Prisma.BotEmpresaCreateOrConnectWithoutDepartamentoInput[]
  createMany?: Prisma.BotEmpresaCreateManyDepartamentoInputEnvelope
  connect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
}

export type BotEmpresaUpdateManyWithoutDepartamentoNestedInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutDepartamentoInput, Prisma.BotEmpresaUncheckedCreateWithoutDepartamentoInput> | Prisma.BotEmpresaCreateWithoutDepartamentoInput[] | Prisma.BotEmpresaUncheckedCreateWithoutDepartamentoInput[]
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutDepartamentoInput | Prisma.BotEmpresaCreateOrConnectWithoutDepartamentoInput[]
  upsert?: Prisma.BotEmpresaUpsertWithWhereUniqueWithoutDepartamentoInput | Prisma.BotEmpresaUpsertWithWhereUniqueWithoutDepartamentoInput[]
  createMany?: Prisma.BotEmpresaCreateManyDepartamentoInputEnvelope
  set?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  disconnect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  delete?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  connect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  update?: Prisma.BotEmpresaUpdateWithWhereUniqueWithoutDepartamentoInput | Prisma.BotEmpresaUpdateWithWhereUniqueWithoutDepartamentoInput[]
  updateMany?: Prisma.BotEmpresaUpdateManyWithWhereWithoutDepartamentoInput | Prisma.BotEmpresaUpdateManyWithWhereWithoutDepartamentoInput[]
  deleteMany?: Prisma.BotEmpresaScalarWhereInput | Prisma.BotEmpresaScalarWhereInput[]
}

export type BotEmpresaUncheckedUpdateManyWithoutDepartamentoNestedInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutDepartamentoInput, Prisma.BotEmpresaUncheckedCreateWithoutDepartamentoInput> | Prisma.BotEmpresaCreateWithoutDepartamentoInput[] | Prisma.BotEmpresaUncheckedCreateWithoutDepartamentoInput[]
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutDepartamentoInput | Prisma.BotEmpresaCreateOrConnectWithoutDepartamentoInput[]
  upsert?: Prisma.BotEmpresaUpsertWithWhereUniqueWithoutDepartamentoInput | Prisma.BotEmpresaUpsertWithWhereUniqueWithoutDepartamentoInput[]
  createMany?: Prisma.BotEmpresaCreateManyDepartamentoInputEnvelope
  set?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  disconnect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  delete?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  connect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  update?: Prisma.BotEmpresaUpdateWithWhereUniqueWithoutDepartamentoInput | Prisma.BotEmpresaUpdateWithWhereUniqueWithoutDepartamentoInput[]
  updateMany?: Prisma.BotEmpresaUpdateManyWithWhereWithoutDepartamentoInput | Prisma.BotEmpresaUpdateManyWithWhereWithoutDepartamentoInput[]
  deleteMany?: Prisma.BotEmpresaScalarWhereInput | Prisma.BotEmpresaScalarWhereInput[]
}

export type BotEmpresaCreateNestedManyWithoutBotInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutBotInput, Prisma.BotEmpresaUncheckedCreateWithoutBotInput> | Prisma.BotEmpresaCreateWithoutBotInput[] | Prisma.BotEmpresaUncheckedCreateWithoutBotInput[]
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutBotInput | Prisma.BotEmpresaCreateOrConnectWithoutBotInput[]
  createMany?: Prisma.BotEmpresaCreateManyBotInputEnvelope
  connect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
}

export type BotEmpresaUncheckedCreateNestedManyWithoutBotInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutBotInput, Prisma.BotEmpresaUncheckedCreateWithoutBotInput> | Prisma.BotEmpresaCreateWithoutBotInput[] | Prisma.BotEmpresaUncheckedCreateWithoutBotInput[]
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutBotInput | Prisma.BotEmpresaCreateOrConnectWithoutBotInput[]
  createMany?: Prisma.BotEmpresaCreateManyBotInputEnvelope
  connect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
}

export type BotEmpresaUpdateManyWithoutBotNestedInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutBotInput, Prisma.BotEmpresaUncheckedCreateWithoutBotInput> | Prisma.BotEmpresaCreateWithoutBotInput[] | Prisma.BotEmpresaUncheckedCreateWithoutBotInput[]
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutBotInput | Prisma.BotEmpresaCreateOrConnectWithoutBotInput[]
  upsert?: Prisma.BotEmpresaUpsertWithWhereUniqueWithoutBotInput | Prisma.BotEmpresaUpsertWithWhereUniqueWithoutBotInput[]
  createMany?: Prisma.BotEmpresaCreateManyBotInputEnvelope
  set?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  disconnect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  delete?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  connect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  update?: Prisma.BotEmpresaUpdateWithWhereUniqueWithoutBotInput | Prisma.BotEmpresaUpdateWithWhereUniqueWithoutBotInput[]
  updateMany?: Prisma.BotEmpresaUpdateManyWithWhereWithoutBotInput | Prisma.BotEmpresaUpdateManyWithWhereWithoutBotInput[]
  deleteMany?: Prisma.BotEmpresaScalarWhereInput | Prisma.BotEmpresaScalarWhereInput[]
}

export type BotEmpresaUncheckedUpdateManyWithoutBotNestedInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutBotInput, Prisma.BotEmpresaUncheckedCreateWithoutBotInput> | Prisma.BotEmpresaCreateWithoutBotInput[] | Prisma.BotEmpresaUncheckedCreateWithoutBotInput[]
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutBotInput | Prisma.BotEmpresaCreateOrConnectWithoutBotInput[]
  upsert?: Prisma.BotEmpresaUpsertWithWhereUniqueWithoutBotInput | Prisma.BotEmpresaUpsertWithWhereUniqueWithoutBotInput[]
  createMany?: Prisma.BotEmpresaCreateManyBotInputEnvelope
  set?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  disconnect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  delete?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  connect?: Prisma.BotEmpresaWhereUniqueInput | Prisma.BotEmpresaWhereUniqueInput[]
  update?: Prisma.BotEmpresaUpdateWithWhereUniqueWithoutBotInput | Prisma.BotEmpresaUpdateWithWhereUniqueWithoutBotInput[]
  updateMany?: Prisma.BotEmpresaUpdateManyWithWhereWithoutBotInput | Prisma.BotEmpresaUpdateManyWithWhereWithoutBotInput[]
  deleteMany?: Prisma.BotEmpresaScalarWhereInput | Prisma.BotEmpresaScalarWhereInput[]
}

export type BotEmpresaCreateNestedOneWithoutFolhas_pagInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutFolhas_pagInput, Prisma.BotEmpresaUncheckedCreateWithoutFolhas_pagInput>
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutFolhas_pagInput
  connect?: Prisma.BotEmpresaWhereUniqueInput
}

export type BotEmpresaUpdateOneRequiredWithoutFolhas_pagNestedInput = {
  create?: Prisma.XOR<Prisma.BotEmpresaCreateWithoutFolhas_pagInput, Prisma.BotEmpresaUncheckedCreateWithoutFolhas_pagInput>
  connectOrCreate?: Prisma.BotEmpresaCreateOrConnectWithoutFolhas_pagInput
  upsert?: Prisma.BotEmpresaUpsertWithoutFolhas_pagInput
  connect?: Prisma.BotEmpresaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BotEmpresaUpdateToOneWithWhereWithoutFolhas_pagInput, Prisma.BotEmpresaUpdateWithoutFolhas_pagInput>, Prisma.BotEmpresaUncheckedUpdateWithoutFolhas_pagInput>
}

export type BotEmpresaCreateWithoutEmpresaInput = {
  id?: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
  bot: Prisma.BotCreateNestedOneWithoutContratosInput
  departamento: Prisma.DepartamentoCreateNestedOneWithoutBotsInput
  folhas_pag?: Prisma.FolhaBotCreateNestedManyWithoutBotEmpresaInput
}

export type BotEmpresaUncheckedCreateWithoutEmpresaInput = {
  id?: string
  botId: string
  departamentoId: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
  folhas_pag?: Prisma.FolhaBotUncheckedCreateNestedManyWithoutBotEmpresaInput
}

export type BotEmpresaCreateOrConnectWithoutEmpresaInput = {
  where: Prisma.BotEmpresaWhereUniqueInput
  create: Prisma.XOR<Prisma.BotEmpresaCreateWithoutEmpresaInput, Prisma.BotEmpresaUncheckedCreateWithoutEmpresaInput>
}

export type BotEmpresaCreateManyEmpresaInputEnvelope = {
  data: Prisma.BotEmpresaCreateManyEmpresaInput | Prisma.BotEmpresaCreateManyEmpresaInput[]
  skipDuplicates?: boolean
}

export type BotEmpresaUpsertWithWhereUniqueWithoutEmpresaInput = {
  where: Prisma.BotEmpresaWhereUniqueInput
  update: Prisma.XOR<Prisma.BotEmpresaUpdateWithoutEmpresaInput, Prisma.BotEmpresaUncheckedUpdateWithoutEmpresaInput>
  create: Prisma.XOR<Prisma.BotEmpresaCreateWithoutEmpresaInput, Prisma.BotEmpresaUncheckedCreateWithoutEmpresaInput>
}

export type BotEmpresaUpdateWithWhereUniqueWithoutEmpresaInput = {
  where: Prisma.BotEmpresaWhereUniqueInput
  data: Prisma.XOR<Prisma.BotEmpresaUpdateWithoutEmpresaInput, Prisma.BotEmpresaUncheckedUpdateWithoutEmpresaInput>
}

export type BotEmpresaUpdateManyWithWhereWithoutEmpresaInput = {
  where: Prisma.BotEmpresaScalarWhereInput
  data: Prisma.XOR<Prisma.BotEmpresaUpdateManyMutationInput, Prisma.BotEmpresaUncheckedUpdateManyWithoutEmpresaInput>
}

export type BotEmpresaScalarWhereInput = {
  AND?: Prisma.BotEmpresaScalarWhereInput | Prisma.BotEmpresaScalarWhereInput[]
  OR?: Prisma.BotEmpresaScalarWhereInput[]
  NOT?: Prisma.BotEmpresaScalarWhereInput | Prisma.BotEmpresaScalarWhereInput[]
  id?: Prisma.StringFilter<"BotEmpresa"> | string
  botId?: Prisma.StringFilter<"BotEmpresa"> | string
  empresaId?: Prisma.StringFilter<"BotEmpresa"> | string
  departamentoId?: Prisma.StringFilter<"BotEmpresa"> | string
  data_contrato?: Prisma.DateTimeFilter<"BotEmpresa"> | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFilter<"BotEmpresa"> | $Enums.ACCOUNT_STATUS
}

export type BotEmpresaCreateWithoutDepartamentoInput = {
  id?: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
  bot: Prisma.BotCreateNestedOneWithoutContratosInput
  empresa: Prisma.EmpresaCreateNestedOneWithoutBots_alocadosInput
  folhas_pag?: Prisma.FolhaBotCreateNestedManyWithoutBotEmpresaInput
}

export type BotEmpresaUncheckedCreateWithoutDepartamentoInput = {
  id?: string
  botId: string
  empresaId: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
  folhas_pag?: Prisma.FolhaBotUncheckedCreateNestedManyWithoutBotEmpresaInput
}

export type BotEmpresaCreateOrConnectWithoutDepartamentoInput = {
  where: Prisma.BotEmpresaWhereUniqueInput
  create: Prisma.XOR<Prisma.BotEmpresaCreateWithoutDepartamentoInput, Prisma.BotEmpresaUncheckedCreateWithoutDepartamentoInput>
}

export type BotEmpresaCreateManyDepartamentoInputEnvelope = {
  data: Prisma.BotEmpresaCreateManyDepartamentoInput | Prisma.BotEmpresaCreateManyDepartamentoInput[]
  skipDuplicates?: boolean
}

export type BotEmpresaUpsertWithWhereUniqueWithoutDepartamentoInput = {
  where: Prisma.BotEmpresaWhereUniqueInput
  update: Prisma.XOR<Prisma.BotEmpresaUpdateWithoutDepartamentoInput, Prisma.BotEmpresaUncheckedUpdateWithoutDepartamentoInput>
  create: Prisma.XOR<Prisma.BotEmpresaCreateWithoutDepartamentoInput, Prisma.BotEmpresaUncheckedCreateWithoutDepartamentoInput>
}

export type BotEmpresaUpdateWithWhereUniqueWithoutDepartamentoInput = {
  where: Prisma.BotEmpresaWhereUniqueInput
  data: Prisma.XOR<Prisma.BotEmpresaUpdateWithoutDepartamentoInput, Prisma.BotEmpresaUncheckedUpdateWithoutDepartamentoInput>
}

export type BotEmpresaUpdateManyWithWhereWithoutDepartamentoInput = {
  where: Prisma.BotEmpresaScalarWhereInput
  data: Prisma.XOR<Prisma.BotEmpresaUpdateManyMutationInput, Prisma.BotEmpresaUncheckedUpdateManyWithoutDepartamentoInput>
}

export type BotEmpresaCreateWithoutBotInput = {
  id?: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
  empresa: Prisma.EmpresaCreateNestedOneWithoutBots_alocadosInput
  departamento: Prisma.DepartamentoCreateNestedOneWithoutBotsInput
  folhas_pag?: Prisma.FolhaBotCreateNestedManyWithoutBotEmpresaInput
}

export type BotEmpresaUncheckedCreateWithoutBotInput = {
  id?: string
  empresaId: string
  departamentoId: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
  folhas_pag?: Prisma.FolhaBotUncheckedCreateNestedManyWithoutBotEmpresaInput
}

export type BotEmpresaCreateOrConnectWithoutBotInput = {
  where: Prisma.BotEmpresaWhereUniqueInput
  create: Prisma.XOR<Prisma.BotEmpresaCreateWithoutBotInput, Prisma.BotEmpresaUncheckedCreateWithoutBotInput>
}

export type BotEmpresaCreateManyBotInputEnvelope = {
  data: Prisma.BotEmpresaCreateManyBotInput | Prisma.BotEmpresaCreateManyBotInput[]
  skipDuplicates?: boolean
}

export type BotEmpresaUpsertWithWhereUniqueWithoutBotInput = {
  where: Prisma.BotEmpresaWhereUniqueInput
  update: Prisma.XOR<Prisma.BotEmpresaUpdateWithoutBotInput, Prisma.BotEmpresaUncheckedUpdateWithoutBotInput>
  create: Prisma.XOR<Prisma.BotEmpresaCreateWithoutBotInput, Prisma.BotEmpresaUncheckedCreateWithoutBotInput>
}

export type BotEmpresaUpdateWithWhereUniqueWithoutBotInput = {
  where: Prisma.BotEmpresaWhereUniqueInput
  data: Prisma.XOR<Prisma.BotEmpresaUpdateWithoutBotInput, Prisma.BotEmpresaUncheckedUpdateWithoutBotInput>
}

export type BotEmpresaUpdateManyWithWhereWithoutBotInput = {
  where: Prisma.BotEmpresaScalarWhereInput
  data: Prisma.XOR<Prisma.BotEmpresaUpdateManyMutationInput, Prisma.BotEmpresaUncheckedUpdateManyWithoutBotInput>
}

export type BotEmpresaCreateWithoutFolhas_pagInput = {
  id?: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
  bot: Prisma.BotCreateNestedOneWithoutContratosInput
  empresa: Prisma.EmpresaCreateNestedOneWithoutBots_alocadosInput
  departamento: Prisma.DepartamentoCreateNestedOneWithoutBotsInput
}

export type BotEmpresaUncheckedCreateWithoutFolhas_pagInput = {
  id?: string
  botId: string
  empresaId: string
  departamentoId: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
}

export type BotEmpresaCreateOrConnectWithoutFolhas_pagInput = {
  where: Prisma.BotEmpresaWhereUniqueInput
  create: Prisma.XOR<Prisma.BotEmpresaCreateWithoutFolhas_pagInput, Prisma.BotEmpresaUncheckedCreateWithoutFolhas_pagInput>
}

export type BotEmpresaUpsertWithoutFolhas_pagInput = {
  update: Prisma.XOR<Prisma.BotEmpresaUpdateWithoutFolhas_pagInput, Prisma.BotEmpresaUncheckedUpdateWithoutFolhas_pagInput>
  create: Prisma.XOR<Prisma.BotEmpresaCreateWithoutFolhas_pagInput, Prisma.BotEmpresaUncheckedCreateWithoutFolhas_pagInput>
  where?: Prisma.BotEmpresaWhereInput
}

export type BotEmpresaUpdateToOneWithWhereWithoutFolhas_pagInput = {
  where?: Prisma.BotEmpresaWhereInput
  data: Prisma.XOR<Prisma.BotEmpresaUpdateWithoutFolhas_pagInput, Prisma.BotEmpresaUncheckedUpdateWithoutFolhas_pagInput>
}

export type BotEmpresaUpdateWithoutFolhas_pagInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
  bot?: Prisma.BotUpdateOneRequiredWithoutContratosNestedInput
  empresa?: Prisma.EmpresaUpdateOneRequiredWithoutBots_alocadosNestedInput
  departamento?: Prisma.DepartamentoUpdateOneRequiredWithoutBotsNestedInput
}

export type BotEmpresaUncheckedUpdateWithoutFolhas_pagInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  botId?: Prisma.StringFieldUpdateOperationsInput | string
  empresaId?: Prisma.StringFieldUpdateOperationsInput | string
  departamentoId?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
}

export type BotEmpresaCreateManyEmpresaInput = {
  id?: string
  botId: string
  departamentoId: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
}

export type BotEmpresaUpdateWithoutEmpresaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
  bot?: Prisma.BotUpdateOneRequiredWithoutContratosNestedInput
  departamento?: Prisma.DepartamentoUpdateOneRequiredWithoutBotsNestedInput
  folhas_pag?: Prisma.FolhaBotUpdateManyWithoutBotEmpresaNestedInput
}

export type BotEmpresaUncheckedUpdateWithoutEmpresaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  botId?: Prisma.StringFieldUpdateOperationsInput | string
  departamentoId?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
  folhas_pag?: Prisma.FolhaBotUncheckedUpdateManyWithoutBotEmpresaNestedInput
}

export type BotEmpresaUncheckedUpdateManyWithoutEmpresaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  botId?: Prisma.StringFieldUpdateOperationsInput | string
  departamentoId?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
}

export type BotEmpresaCreateManyDepartamentoInput = {
  id?: string
  botId: string
  empresaId: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
}

export type BotEmpresaUpdateWithoutDepartamentoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
  bot?: Prisma.BotUpdateOneRequiredWithoutContratosNestedInput
  empresa?: Prisma.EmpresaUpdateOneRequiredWithoutBots_alocadosNestedInput
  folhas_pag?: Prisma.FolhaBotUpdateManyWithoutBotEmpresaNestedInput
}

export type BotEmpresaUncheckedUpdateWithoutDepartamentoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  botId?: Prisma.StringFieldUpdateOperationsInput | string
  empresaId?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
  folhas_pag?: Prisma.FolhaBotUncheckedUpdateManyWithoutBotEmpresaNestedInput
}

export type BotEmpresaUncheckedUpdateManyWithoutDepartamentoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  botId?: Prisma.StringFieldUpdateOperationsInput | string
  empresaId?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
}

export type BotEmpresaCreateManyBotInput = {
  id?: string
  empresaId: string
  departamentoId: string
  data_contrato?: Date | string
  status?: $Enums.ACCOUNT_STATUS
}

export type BotEmpresaUpdateWithoutBotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
  empresa?: Prisma.EmpresaUpdateOneRequiredWithoutBots_alocadosNestedInput
  departamento?: Prisma.DepartamentoUpdateOneRequiredWithoutBotsNestedInput
  folhas_pag?: Prisma.FolhaBotUpdateManyWithoutBotEmpresaNestedInput
}

export type BotEmpresaUncheckedUpdateWithoutBotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  empresaId?: Prisma.StringFieldUpdateOperationsInput | string
  departamentoId?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
  folhas_pag?: Prisma.FolhaBotUncheckedUpdateManyWithoutBotEmpresaNestedInput
}

export type BotEmpresaUncheckedUpdateManyWithoutBotInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  empresaId?: Prisma.StringFieldUpdateOperationsInput | string
  departamentoId?: Prisma.StringFieldUpdateOperationsInput | string
  data_contrato?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumACCOUNT_STATUSFieldUpdateOperationsInput | $Enums.ACCOUNT_STATUS
}


/**
 * Count Type BotEmpresaCountOutputType
 */

export type BotEmpresaCountOutputType = {
  folhas_pag: number
}

export type BotEmpresaCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  folhas_pag?: boolean | BotEmpresaCountOutputTypeCountFolhas_pagArgs
}

/**
 * BotEmpresaCountOutputType without action
 */
export type BotEmpresaCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresaCountOutputType
   */
  select?: Prisma.BotEmpresaCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BotEmpresaCountOutputType without action
 */
export type BotEmpresaCountOutputTypeCountFolhas_pagArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FolhaBotWhereInput
}


export type BotEmpresaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  botId?: boolean
  empresaId?: boolean
  departamentoId?: boolean
  data_contrato?: boolean
  status?: boolean
  bot?: boolean | Prisma.BotDefaultArgs<ExtArgs>
  empresa?: boolean | Prisma.EmpresaDefaultArgs<ExtArgs>
  departamento?: boolean | Prisma.DepartamentoDefaultArgs<ExtArgs>
  folhas_pag?: boolean | Prisma.BotEmpresa$folhas_pagArgs<ExtArgs>
  _count?: boolean | Prisma.BotEmpresaCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["botEmpresa"]>

export type BotEmpresaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  botId?: boolean
  empresaId?: boolean
  departamentoId?: boolean
  data_contrato?: boolean
  status?: boolean
  bot?: boolean | Prisma.BotDefaultArgs<ExtArgs>
  empresa?: boolean | Prisma.EmpresaDefaultArgs<ExtArgs>
  departamento?: boolean | Prisma.DepartamentoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["botEmpresa"]>

export type BotEmpresaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  botId?: boolean
  empresaId?: boolean
  departamentoId?: boolean
  data_contrato?: boolean
  status?: boolean
  bot?: boolean | Prisma.BotDefaultArgs<ExtArgs>
  empresa?: boolean | Prisma.EmpresaDefaultArgs<ExtArgs>
  departamento?: boolean | Prisma.DepartamentoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["botEmpresa"]>

export type BotEmpresaSelectScalar = {
  id?: boolean
  botId?: boolean
  empresaId?: boolean
  departamentoId?: boolean
  data_contrato?: boolean
  status?: boolean
}

export type BotEmpresaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "botId" | "empresaId" | "departamentoId" | "data_contrato" | "status", ExtArgs["result"]["botEmpresa"]>
export type BotEmpresaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bot?: boolean | Prisma.BotDefaultArgs<ExtArgs>
  empresa?: boolean | Prisma.EmpresaDefaultArgs<ExtArgs>
  departamento?: boolean | Prisma.DepartamentoDefaultArgs<ExtArgs>
  folhas_pag?: boolean | Prisma.BotEmpresa$folhas_pagArgs<ExtArgs>
  _count?: boolean | Prisma.BotEmpresaCountOutputTypeDefaultArgs<ExtArgs>
}
export type BotEmpresaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bot?: boolean | Prisma.BotDefaultArgs<ExtArgs>
  empresa?: boolean | Prisma.EmpresaDefaultArgs<ExtArgs>
  departamento?: boolean | Prisma.DepartamentoDefaultArgs<ExtArgs>
}
export type BotEmpresaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bot?: boolean | Prisma.BotDefaultArgs<ExtArgs>
  empresa?: boolean | Prisma.EmpresaDefaultArgs<ExtArgs>
  departamento?: boolean | Prisma.DepartamentoDefaultArgs<ExtArgs>
}

export type $BotEmpresaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BotEmpresa"
  objects: {
    bot: Prisma.$BotPayload<ExtArgs>
    empresa: Prisma.$EmpresaPayload<ExtArgs>
    departamento: Prisma.$DepartamentoPayload<ExtArgs>
    folhas_pag: Prisma.$FolhaBotPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    botId: string
    empresaId: string
    departamentoId: string
    data_contrato: Date
    status: $Enums.ACCOUNT_STATUS
  }, ExtArgs["result"]["botEmpresa"]>
  composites: {}
}

export type BotEmpresaGetPayload<S extends boolean | null | undefined | BotEmpresaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BotEmpresaPayload, S>

export type BotEmpresaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BotEmpresaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BotEmpresaCountAggregateInputType | true
  }

export interface BotEmpresaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BotEmpresa'], meta: { name: 'BotEmpresa' } }
  /**
   * Find zero or one BotEmpresa that matches the filter.
   * @param {BotEmpresaFindUniqueArgs} args - Arguments to find a BotEmpresa
   * @example
   * // Get one BotEmpresa
   * const botEmpresa = await prisma.botEmpresa.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BotEmpresaFindUniqueArgs>(args: Prisma.SelectSubset<T, BotEmpresaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BotEmpresaClient<runtime.Types.Result.GetResult<Prisma.$BotEmpresaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BotEmpresa that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BotEmpresaFindUniqueOrThrowArgs} args - Arguments to find a BotEmpresa
   * @example
   * // Get one BotEmpresa
   * const botEmpresa = await prisma.botEmpresa.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BotEmpresaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BotEmpresaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BotEmpresaClient<runtime.Types.Result.GetResult<Prisma.$BotEmpresaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BotEmpresa that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotEmpresaFindFirstArgs} args - Arguments to find a BotEmpresa
   * @example
   * // Get one BotEmpresa
   * const botEmpresa = await prisma.botEmpresa.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BotEmpresaFindFirstArgs>(args?: Prisma.SelectSubset<T, BotEmpresaFindFirstArgs<ExtArgs>>): Prisma.Prisma__BotEmpresaClient<runtime.Types.Result.GetResult<Prisma.$BotEmpresaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BotEmpresa that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotEmpresaFindFirstOrThrowArgs} args - Arguments to find a BotEmpresa
   * @example
   * // Get one BotEmpresa
   * const botEmpresa = await prisma.botEmpresa.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BotEmpresaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BotEmpresaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BotEmpresaClient<runtime.Types.Result.GetResult<Prisma.$BotEmpresaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BotEmpresas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotEmpresaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BotEmpresas
   * const botEmpresas = await prisma.botEmpresa.findMany()
   * 
   * // Get first 10 BotEmpresas
   * const botEmpresas = await prisma.botEmpresa.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const botEmpresaWithIdOnly = await prisma.botEmpresa.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BotEmpresaFindManyArgs>(args?: Prisma.SelectSubset<T, BotEmpresaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BotEmpresaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BotEmpresa.
   * @param {BotEmpresaCreateArgs} args - Arguments to create a BotEmpresa.
   * @example
   * // Create one BotEmpresa
   * const BotEmpresa = await prisma.botEmpresa.create({
   *   data: {
   *     // ... data to create a BotEmpresa
   *   }
   * })
   * 
   */
  create<T extends BotEmpresaCreateArgs>(args: Prisma.SelectSubset<T, BotEmpresaCreateArgs<ExtArgs>>): Prisma.Prisma__BotEmpresaClient<runtime.Types.Result.GetResult<Prisma.$BotEmpresaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BotEmpresas.
   * @param {BotEmpresaCreateManyArgs} args - Arguments to create many BotEmpresas.
   * @example
   * // Create many BotEmpresas
   * const botEmpresa = await prisma.botEmpresa.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BotEmpresaCreateManyArgs>(args?: Prisma.SelectSubset<T, BotEmpresaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BotEmpresas and returns the data saved in the database.
   * @param {BotEmpresaCreateManyAndReturnArgs} args - Arguments to create many BotEmpresas.
   * @example
   * // Create many BotEmpresas
   * const botEmpresa = await prisma.botEmpresa.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BotEmpresas and only return the `id`
   * const botEmpresaWithIdOnly = await prisma.botEmpresa.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BotEmpresaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BotEmpresaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BotEmpresaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BotEmpresa.
   * @param {BotEmpresaDeleteArgs} args - Arguments to delete one BotEmpresa.
   * @example
   * // Delete one BotEmpresa
   * const BotEmpresa = await prisma.botEmpresa.delete({
   *   where: {
   *     // ... filter to delete one BotEmpresa
   *   }
   * })
   * 
   */
  delete<T extends BotEmpresaDeleteArgs>(args: Prisma.SelectSubset<T, BotEmpresaDeleteArgs<ExtArgs>>): Prisma.Prisma__BotEmpresaClient<runtime.Types.Result.GetResult<Prisma.$BotEmpresaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BotEmpresa.
   * @param {BotEmpresaUpdateArgs} args - Arguments to update one BotEmpresa.
   * @example
   * // Update one BotEmpresa
   * const botEmpresa = await prisma.botEmpresa.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BotEmpresaUpdateArgs>(args: Prisma.SelectSubset<T, BotEmpresaUpdateArgs<ExtArgs>>): Prisma.Prisma__BotEmpresaClient<runtime.Types.Result.GetResult<Prisma.$BotEmpresaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BotEmpresas.
   * @param {BotEmpresaDeleteManyArgs} args - Arguments to filter BotEmpresas to delete.
   * @example
   * // Delete a few BotEmpresas
   * const { count } = await prisma.botEmpresa.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BotEmpresaDeleteManyArgs>(args?: Prisma.SelectSubset<T, BotEmpresaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BotEmpresas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotEmpresaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BotEmpresas
   * const botEmpresa = await prisma.botEmpresa.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BotEmpresaUpdateManyArgs>(args: Prisma.SelectSubset<T, BotEmpresaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BotEmpresas and returns the data updated in the database.
   * @param {BotEmpresaUpdateManyAndReturnArgs} args - Arguments to update many BotEmpresas.
   * @example
   * // Update many BotEmpresas
   * const botEmpresa = await prisma.botEmpresa.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BotEmpresas and only return the `id`
   * const botEmpresaWithIdOnly = await prisma.botEmpresa.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BotEmpresaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BotEmpresaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BotEmpresaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BotEmpresa.
   * @param {BotEmpresaUpsertArgs} args - Arguments to update or create a BotEmpresa.
   * @example
   * // Update or create a BotEmpresa
   * const botEmpresa = await prisma.botEmpresa.upsert({
   *   create: {
   *     // ... data to create a BotEmpresa
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BotEmpresa we want to update
   *   }
   * })
   */
  upsert<T extends BotEmpresaUpsertArgs>(args: Prisma.SelectSubset<T, BotEmpresaUpsertArgs<ExtArgs>>): Prisma.Prisma__BotEmpresaClient<runtime.Types.Result.GetResult<Prisma.$BotEmpresaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BotEmpresas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotEmpresaCountArgs} args - Arguments to filter BotEmpresas to count.
   * @example
   * // Count the number of BotEmpresas
   * const count = await prisma.botEmpresa.count({
   *   where: {
   *     // ... the filter for the BotEmpresas we want to count
   *   }
   * })
  **/
  count<T extends BotEmpresaCountArgs>(
    args?: Prisma.Subset<T, BotEmpresaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BotEmpresaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BotEmpresa.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotEmpresaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BotEmpresaAggregateArgs>(args: Prisma.Subset<T, BotEmpresaAggregateArgs>): Prisma.PrismaPromise<GetBotEmpresaAggregateType<T>>

  /**
   * Group by BotEmpresa.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BotEmpresaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BotEmpresaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BotEmpresaGroupByArgs['orderBy'] }
      : { orderBy?: BotEmpresaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BotEmpresaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBotEmpresaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BotEmpresa model
 */
readonly fields: BotEmpresaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BotEmpresa.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BotEmpresaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bot<T extends Prisma.BotDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BotDefaultArgs<ExtArgs>>): Prisma.Prisma__BotClient<runtime.Types.Result.GetResult<Prisma.$BotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  empresa<T extends Prisma.EmpresaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EmpresaDefaultArgs<ExtArgs>>): Prisma.Prisma__EmpresaClient<runtime.Types.Result.GetResult<Prisma.$EmpresaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  departamento<T extends Prisma.DepartamentoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DepartamentoDefaultArgs<ExtArgs>>): Prisma.Prisma__DepartamentoClient<runtime.Types.Result.GetResult<Prisma.$DepartamentoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  folhas_pag<T extends Prisma.BotEmpresa$folhas_pagArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BotEmpresa$folhas_pagArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FolhaBotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BotEmpresa model
 */
export interface BotEmpresaFieldRefs {
  readonly id: Prisma.FieldRef<"BotEmpresa", 'String'>
  readonly botId: Prisma.FieldRef<"BotEmpresa", 'String'>
  readonly empresaId: Prisma.FieldRef<"BotEmpresa", 'String'>
  readonly departamentoId: Prisma.FieldRef<"BotEmpresa", 'String'>
  readonly data_contrato: Prisma.FieldRef<"BotEmpresa", 'DateTime'>
  readonly status: Prisma.FieldRef<"BotEmpresa", 'ACCOUNT_STATUS'>
}
    

// Custom InputTypes
/**
 * BotEmpresa findUnique
 */
export type BotEmpresaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresa
   */
  select?: Prisma.BotEmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotEmpresa
   */
  omit?: Prisma.BotEmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotEmpresaInclude<ExtArgs> | null
  /**
   * Filter, which BotEmpresa to fetch.
   */
  where: Prisma.BotEmpresaWhereUniqueInput
}

/**
 * BotEmpresa findUniqueOrThrow
 */
export type BotEmpresaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresa
   */
  select?: Prisma.BotEmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotEmpresa
   */
  omit?: Prisma.BotEmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotEmpresaInclude<ExtArgs> | null
  /**
   * Filter, which BotEmpresa to fetch.
   */
  where: Prisma.BotEmpresaWhereUniqueInput
}

/**
 * BotEmpresa findFirst
 */
export type BotEmpresaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresa
   */
  select?: Prisma.BotEmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotEmpresa
   */
  omit?: Prisma.BotEmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotEmpresaInclude<ExtArgs> | null
  /**
   * Filter, which BotEmpresa to fetch.
   */
  where?: Prisma.BotEmpresaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BotEmpresas to fetch.
   */
  orderBy?: Prisma.BotEmpresaOrderByWithRelationInput | Prisma.BotEmpresaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BotEmpresas.
   */
  cursor?: Prisma.BotEmpresaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BotEmpresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BotEmpresas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BotEmpresas.
   */
  distinct?: Prisma.BotEmpresaScalarFieldEnum | Prisma.BotEmpresaScalarFieldEnum[]
}

/**
 * BotEmpresa findFirstOrThrow
 */
export type BotEmpresaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresa
   */
  select?: Prisma.BotEmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotEmpresa
   */
  omit?: Prisma.BotEmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotEmpresaInclude<ExtArgs> | null
  /**
   * Filter, which BotEmpresa to fetch.
   */
  where?: Prisma.BotEmpresaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BotEmpresas to fetch.
   */
  orderBy?: Prisma.BotEmpresaOrderByWithRelationInput | Prisma.BotEmpresaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BotEmpresas.
   */
  cursor?: Prisma.BotEmpresaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BotEmpresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BotEmpresas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BotEmpresas.
   */
  distinct?: Prisma.BotEmpresaScalarFieldEnum | Prisma.BotEmpresaScalarFieldEnum[]
}

/**
 * BotEmpresa findMany
 */
export type BotEmpresaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresa
   */
  select?: Prisma.BotEmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotEmpresa
   */
  omit?: Prisma.BotEmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotEmpresaInclude<ExtArgs> | null
  /**
   * Filter, which BotEmpresas to fetch.
   */
  where?: Prisma.BotEmpresaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BotEmpresas to fetch.
   */
  orderBy?: Prisma.BotEmpresaOrderByWithRelationInput | Prisma.BotEmpresaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BotEmpresas.
   */
  cursor?: Prisma.BotEmpresaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BotEmpresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BotEmpresas.
   */
  skip?: number
  distinct?: Prisma.BotEmpresaScalarFieldEnum | Prisma.BotEmpresaScalarFieldEnum[]
}

/**
 * BotEmpresa create
 */
export type BotEmpresaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresa
   */
  select?: Prisma.BotEmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotEmpresa
   */
  omit?: Prisma.BotEmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotEmpresaInclude<ExtArgs> | null
  /**
   * The data needed to create a BotEmpresa.
   */
  data: Prisma.XOR<Prisma.BotEmpresaCreateInput, Prisma.BotEmpresaUncheckedCreateInput>
}

/**
 * BotEmpresa createMany
 */
export type BotEmpresaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BotEmpresas.
   */
  data: Prisma.BotEmpresaCreateManyInput | Prisma.BotEmpresaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BotEmpresa createManyAndReturn
 */
export type BotEmpresaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresa
   */
  select?: Prisma.BotEmpresaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BotEmpresa
   */
  omit?: Prisma.BotEmpresaOmit<ExtArgs> | null
  /**
   * The data used to create many BotEmpresas.
   */
  data: Prisma.BotEmpresaCreateManyInput | Prisma.BotEmpresaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotEmpresaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BotEmpresa update
 */
export type BotEmpresaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresa
   */
  select?: Prisma.BotEmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotEmpresa
   */
  omit?: Prisma.BotEmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotEmpresaInclude<ExtArgs> | null
  /**
   * The data needed to update a BotEmpresa.
   */
  data: Prisma.XOR<Prisma.BotEmpresaUpdateInput, Prisma.BotEmpresaUncheckedUpdateInput>
  /**
   * Choose, which BotEmpresa to update.
   */
  where: Prisma.BotEmpresaWhereUniqueInput
}

/**
 * BotEmpresa updateMany
 */
export type BotEmpresaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BotEmpresas.
   */
  data: Prisma.XOR<Prisma.BotEmpresaUpdateManyMutationInput, Prisma.BotEmpresaUncheckedUpdateManyInput>
  /**
   * Filter which BotEmpresas to update
   */
  where?: Prisma.BotEmpresaWhereInput
  /**
   * Limit how many BotEmpresas to update.
   */
  limit?: number
}

/**
 * BotEmpresa updateManyAndReturn
 */
export type BotEmpresaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresa
   */
  select?: Prisma.BotEmpresaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BotEmpresa
   */
  omit?: Prisma.BotEmpresaOmit<ExtArgs> | null
  /**
   * The data used to update BotEmpresas.
   */
  data: Prisma.XOR<Prisma.BotEmpresaUpdateManyMutationInput, Prisma.BotEmpresaUncheckedUpdateManyInput>
  /**
   * Filter which BotEmpresas to update
   */
  where?: Prisma.BotEmpresaWhereInput
  /**
   * Limit how many BotEmpresas to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotEmpresaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BotEmpresa upsert
 */
export type BotEmpresaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresa
   */
  select?: Prisma.BotEmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotEmpresa
   */
  omit?: Prisma.BotEmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotEmpresaInclude<ExtArgs> | null
  /**
   * The filter to search for the BotEmpresa to update in case it exists.
   */
  where: Prisma.BotEmpresaWhereUniqueInput
  /**
   * In case the BotEmpresa found by the `where` argument doesn't exist, create a new BotEmpresa with this data.
   */
  create: Prisma.XOR<Prisma.BotEmpresaCreateInput, Prisma.BotEmpresaUncheckedCreateInput>
  /**
   * In case the BotEmpresa was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BotEmpresaUpdateInput, Prisma.BotEmpresaUncheckedUpdateInput>
}

/**
 * BotEmpresa delete
 */
export type BotEmpresaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresa
   */
  select?: Prisma.BotEmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotEmpresa
   */
  omit?: Prisma.BotEmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotEmpresaInclude<ExtArgs> | null
  /**
   * Filter which BotEmpresa to delete.
   */
  where: Prisma.BotEmpresaWhereUniqueInput
}

/**
 * BotEmpresa deleteMany
 */
export type BotEmpresaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BotEmpresas to delete
   */
  where?: Prisma.BotEmpresaWhereInput
  /**
   * Limit how many BotEmpresas to delete.
   */
  limit?: number
}

/**
 * BotEmpresa.folhas_pag
 */
export type BotEmpresa$folhas_pagArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FolhaBot
   */
  select?: Prisma.FolhaBotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FolhaBot
   */
  omit?: Prisma.FolhaBotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FolhaBotInclude<ExtArgs> | null
  where?: Prisma.FolhaBotWhereInput
  orderBy?: Prisma.FolhaBotOrderByWithRelationInput | Prisma.FolhaBotOrderByWithRelationInput[]
  cursor?: Prisma.FolhaBotWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FolhaBotScalarFieldEnum | Prisma.FolhaBotScalarFieldEnum[]
}

/**
 * BotEmpresa without action
 */
export type BotEmpresaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresa
   */
  select?: Prisma.BotEmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotEmpresa
   */
  omit?: Prisma.BotEmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotEmpresaInclude<ExtArgs> | null
}
