
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Empresa` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Empresa
 * 
 */
export type EmpresaModel = runtime.Types.Result.DefaultSelection<Prisma.$EmpresaPayload>

export type AggregateEmpresa = {
  _count: EmpresaCountAggregateOutputType | null
  _min: EmpresaMinAggregateOutputType | null
  _max: EmpresaMaxAggregateOutputType | null
}

export type EmpresaMinAggregateOutputType = {
  id: string | null
  nome: string | null
  sector: string | null
  website: string | null
  logotipo: string | null
  cor_primaria: string | null
  created_at: Date | null
  usuarioId: string | null
}

export type EmpresaMaxAggregateOutputType = {
  id: string | null
  nome: string | null
  sector: string | null
  website: string | null
  logotipo: string | null
  cor_primaria: string | null
  created_at: Date | null
  usuarioId: string | null
}

export type EmpresaCountAggregateOutputType = {
  id: number
  nome: number
  sector: number
  website: number
  logotipo: number
  cor_primaria: number
  created_at: number
  usuarioId: number
  _all: number
}


export type EmpresaMinAggregateInputType = {
  id?: true
  nome?: true
  sector?: true
  website?: true
  logotipo?: true
  cor_primaria?: true
  created_at?: true
  usuarioId?: true
}

export type EmpresaMaxAggregateInputType = {
  id?: true
  nome?: true
  sector?: true
  website?: true
  logotipo?: true
  cor_primaria?: true
  created_at?: true
  usuarioId?: true
}

export type EmpresaCountAggregateInputType = {
  id?: true
  nome?: true
  sector?: true
  website?: true
  logotipo?: true
  cor_primaria?: true
  created_at?: true
  usuarioId?: true
  _all?: true
}

export type EmpresaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Empresa to aggregate.
   */
  where?: Prisma.EmpresaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Empresas to fetch.
   */
  orderBy?: Prisma.EmpresaOrderByWithRelationInput | Prisma.EmpresaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EmpresaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Empresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Empresas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Empresas
  **/
  _count?: true | EmpresaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmpresaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmpresaMaxAggregateInputType
}

export type GetEmpresaAggregateType<T extends EmpresaAggregateArgs> = {
      [P in keyof T & keyof AggregateEmpresa]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmpresa[P]>
    : Prisma.GetScalarType<T[P], AggregateEmpresa[P]>
}




export type EmpresaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmpresaWhereInput
  orderBy?: Prisma.EmpresaOrderByWithAggregationInput | Prisma.EmpresaOrderByWithAggregationInput[]
  by: Prisma.EmpresaScalarFieldEnum[] | Prisma.EmpresaScalarFieldEnum
  having?: Prisma.EmpresaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmpresaCountAggregateInputType | true
  _min?: EmpresaMinAggregateInputType
  _max?: EmpresaMaxAggregateInputType
}

export type EmpresaGroupByOutputType = {
  id: string
  nome: string
  sector: string
  website: string | null
  logotipo: string | null
  cor_primaria: string | null
  created_at: Date
  usuarioId: string
  _count: EmpresaCountAggregateOutputType | null
  _min: EmpresaMinAggregateOutputType | null
  _max: EmpresaMaxAggregateOutputType | null
}

type GetEmpresaGroupByPayload<T extends EmpresaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmpresaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmpresaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmpresaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmpresaGroupByOutputType[P]>
      }
    >
  >



export type EmpresaWhereInput = {
  AND?: Prisma.EmpresaWhereInput | Prisma.EmpresaWhereInput[]
  OR?: Prisma.EmpresaWhereInput[]
  NOT?: Prisma.EmpresaWhereInput | Prisma.EmpresaWhereInput[]
  id?: Prisma.StringFilter<"Empresa"> | string
  nome?: Prisma.StringFilter<"Empresa"> | string
  sector?: Prisma.StringFilter<"Empresa"> | string
  website?: Prisma.StringNullableFilter<"Empresa"> | string | null
  logotipo?: Prisma.StringNullableFilter<"Empresa"> | string | null
  cor_primaria?: Prisma.StringNullableFilter<"Empresa"> | string | null
  created_at?: Prisma.DateTimeFilter<"Empresa"> | Date | string
  usuarioId?: Prisma.StringFilter<"Empresa"> | string
  usuario?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
  departamentos?: Prisma.DepartamentoListRelationFilter
  transacoes?: Prisma.TransacaoListRelationFilter
  arquivos?: Prisma.ArquivoListRelationFilter
  bots_alocados?: Prisma.BotEmpresaListRelationFilter
}

export type EmpresaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  sector?: Prisma.SortOrder
  website?: Prisma.SortOrderInput | Prisma.SortOrder
  logotipo?: Prisma.SortOrderInput | Prisma.SortOrder
  cor_primaria?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
  usuario?: Prisma.UsuarioOrderByWithRelationInput
  departamentos?: Prisma.DepartamentoOrderByRelationAggregateInput
  transacoes?: Prisma.TransacaoOrderByRelationAggregateInput
  arquivos?: Prisma.ArquivoOrderByRelationAggregateInput
  bots_alocados?: Prisma.BotEmpresaOrderByRelationAggregateInput
}

export type EmpresaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EmpresaWhereInput | Prisma.EmpresaWhereInput[]
  OR?: Prisma.EmpresaWhereInput[]
  NOT?: Prisma.EmpresaWhereInput | Prisma.EmpresaWhereInput[]
  nome?: Prisma.StringFilter<"Empresa"> | string
  sector?: Prisma.StringFilter<"Empresa"> | string
  website?: Prisma.StringNullableFilter<"Empresa"> | string | null
  logotipo?: Prisma.StringNullableFilter<"Empresa"> | string | null
  cor_primaria?: Prisma.StringNullableFilter<"Empresa"> | string | null
  created_at?: Prisma.DateTimeFilter<"Empresa"> | Date | string
  usuarioId?: Prisma.StringFilter<"Empresa"> | string
  usuario?: Prisma.XOR<Prisma.UsuarioScalarRelationFilter, Prisma.UsuarioWhereInput>
  departamentos?: Prisma.DepartamentoListRelationFilter
  transacoes?: Prisma.TransacaoListRelationFilter
  arquivos?: Prisma.ArquivoListRelationFilter
  bots_alocados?: Prisma.BotEmpresaListRelationFilter
}, "id">

export type EmpresaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  sector?: Prisma.SortOrder
  website?: Prisma.SortOrderInput | Prisma.SortOrder
  logotipo?: Prisma.SortOrderInput | Prisma.SortOrder
  cor_primaria?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
  _count?: Prisma.EmpresaCountOrderByAggregateInput
  _max?: Prisma.EmpresaMaxOrderByAggregateInput
  _min?: Prisma.EmpresaMinOrderByAggregateInput
}

export type EmpresaScalarWhereWithAggregatesInput = {
  AND?: Prisma.EmpresaScalarWhereWithAggregatesInput | Prisma.EmpresaScalarWhereWithAggregatesInput[]
  OR?: Prisma.EmpresaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EmpresaScalarWhereWithAggregatesInput | Prisma.EmpresaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Empresa"> | string
  nome?: Prisma.StringWithAggregatesFilter<"Empresa"> | string
  sector?: Prisma.StringWithAggregatesFilter<"Empresa"> | string
  website?: Prisma.StringNullableWithAggregatesFilter<"Empresa"> | string | null
  logotipo?: Prisma.StringNullableWithAggregatesFilter<"Empresa"> | string | null
  cor_primaria?: Prisma.StringNullableWithAggregatesFilter<"Empresa"> | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Empresa"> | Date | string
  usuarioId?: Prisma.StringWithAggregatesFilter<"Empresa"> | string
}

export type EmpresaCreateInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutEmpresasInput
  departamentos?: Prisma.DepartamentoCreateNestedManyWithoutEmpresaInput
  transacoes?: Prisma.TransacaoCreateNestedManyWithoutEmpresaInput
  arquivos?: Prisma.ArquivoCreateNestedManyWithoutEmpresaInput
  bots_alocados?: Prisma.BotEmpresaCreateNestedManyWithoutEmpresaInput
}

export type EmpresaUncheckedCreateInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
  usuarioId: string
  departamentos?: Prisma.DepartamentoUncheckedCreateNestedManyWithoutEmpresaInput
  transacoes?: Prisma.TransacaoUncheckedCreateNestedManyWithoutEmpresaInput
  arquivos?: Prisma.ArquivoUncheckedCreateNestedManyWithoutEmpresaInput
  bots_alocados?: Prisma.BotEmpresaUncheckedCreateNestedManyWithoutEmpresaInput
}

export type EmpresaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutEmpresasNestedInput
  departamentos?: Prisma.DepartamentoUpdateManyWithoutEmpresaNestedInput
  transacoes?: Prisma.TransacaoUpdateManyWithoutEmpresaNestedInput
  arquivos?: Prisma.ArquivoUpdateManyWithoutEmpresaNestedInput
  bots_alocados?: Prisma.BotEmpresaUpdateManyWithoutEmpresaNestedInput
}

export type EmpresaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  departamentos?: Prisma.DepartamentoUncheckedUpdateManyWithoutEmpresaNestedInput
  transacoes?: Prisma.TransacaoUncheckedUpdateManyWithoutEmpresaNestedInput
  arquivos?: Prisma.ArquivoUncheckedUpdateManyWithoutEmpresaNestedInput
  bots_alocados?: Prisma.BotEmpresaUncheckedUpdateManyWithoutEmpresaNestedInput
}

export type EmpresaCreateManyInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
  usuarioId: string
}

export type EmpresaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmpresaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type EmpresaListRelationFilter = {
  every?: Prisma.EmpresaWhereInput
  some?: Prisma.EmpresaWhereInput
  none?: Prisma.EmpresaWhereInput
}

export type EmpresaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EmpresaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  sector?: Prisma.SortOrder
  website?: Prisma.SortOrder
  logotipo?: Prisma.SortOrder
  cor_primaria?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
}

export type EmpresaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  sector?: Prisma.SortOrder
  website?: Prisma.SortOrder
  logotipo?: Prisma.SortOrder
  cor_primaria?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
}

export type EmpresaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  sector?: Prisma.SortOrder
  website?: Prisma.SortOrder
  logotipo?: Prisma.SortOrder
  cor_primaria?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  usuarioId?: Prisma.SortOrder
}

export type EmpresaScalarRelationFilter = {
  is?: Prisma.EmpresaWhereInput
  isNot?: Prisma.EmpresaWhereInput
}

export type EmpresaCreateNestedManyWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.EmpresaCreateWithoutUsuarioInput, Prisma.EmpresaUncheckedCreateWithoutUsuarioInput> | Prisma.EmpresaCreateWithoutUsuarioInput[] | Prisma.EmpresaUncheckedCreateWithoutUsuarioInput[]
  connectOrCreate?: Prisma.EmpresaCreateOrConnectWithoutUsuarioInput | Prisma.EmpresaCreateOrConnectWithoutUsuarioInput[]
  createMany?: Prisma.EmpresaCreateManyUsuarioInputEnvelope
  connect?: Prisma.EmpresaWhereUniqueInput | Prisma.EmpresaWhereUniqueInput[]
}

export type EmpresaUncheckedCreateNestedManyWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.EmpresaCreateWithoutUsuarioInput, Prisma.EmpresaUncheckedCreateWithoutUsuarioInput> | Prisma.EmpresaCreateWithoutUsuarioInput[] | Prisma.EmpresaUncheckedCreateWithoutUsuarioInput[]
  connectOrCreate?: Prisma.EmpresaCreateOrConnectWithoutUsuarioInput | Prisma.EmpresaCreateOrConnectWithoutUsuarioInput[]
  createMany?: Prisma.EmpresaCreateManyUsuarioInputEnvelope
  connect?: Prisma.EmpresaWhereUniqueInput | Prisma.EmpresaWhereUniqueInput[]
}

export type EmpresaUpdateManyWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.EmpresaCreateWithoutUsuarioInput, Prisma.EmpresaUncheckedCreateWithoutUsuarioInput> | Prisma.EmpresaCreateWithoutUsuarioInput[] | Prisma.EmpresaUncheckedCreateWithoutUsuarioInput[]
  connectOrCreate?: Prisma.EmpresaCreateOrConnectWithoutUsuarioInput | Prisma.EmpresaCreateOrConnectWithoutUsuarioInput[]
  upsert?: Prisma.EmpresaUpsertWithWhereUniqueWithoutUsuarioInput | Prisma.EmpresaUpsertWithWhereUniqueWithoutUsuarioInput[]
  createMany?: Prisma.EmpresaCreateManyUsuarioInputEnvelope
  set?: Prisma.EmpresaWhereUniqueInput | Prisma.EmpresaWhereUniqueInput[]
  disconnect?: Prisma.EmpresaWhereUniqueInput | Prisma.EmpresaWhereUniqueInput[]
  delete?: Prisma.EmpresaWhereUniqueInput | Prisma.EmpresaWhereUniqueInput[]
  connect?: Prisma.EmpresaWhereUniqueInput | Prisma.EmpresaWhereUniqueInput[]
  update?: Prisma.EmpresaUpdateWithWhereUniqueWithoutUsuarioInput | Prisma.EmpresaUpdateWithWhereUniqueWithoutUsuarioInput[]
  updateMany?: Prisma.EmpresaUpdateManyWithWhereWithoutUsuarioInput | Prisma.EmpresaUpdateManyWithWhereWithoutUsuarioInput[]
  deleteMany?: Prisma.EmpresaScalarWhereInput | Prisma.EmpresaScalarWhereInput[]
}

export type EmpresaUncheckedUpdateManyWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.EmpresaCreateWithoutUsuarioInput, Prisma.EmpresaUncheckedCreateWithoutUsuarioInput> | Prisma.EmpresaCreateWithoutUsuarioInput[] | Prisma.EmpresaUncheckedCreateWithoutUsuarioInput[]
  connectOrCreate?: Prisma.EmpresaCreateOrConnectWithoutUsuarioInput | Prisma.EmpresaCreateOrConnectWithoutUsuarioInput[]
  upsert?: Prisma.EmpresaUpsertWithWhereUniqueWithoutUsuarioInput | Prisma.EmpresaUpsertWithWhereUniqueWithoutUsuarioInput[]
  createMany?: Prisma.EmpresaCreateManyUsuarioInputEnvelope
  set?: Prisma.EmpresaWhereUniqueInput | Prisma.EmpresaWhereUniqueInput[]
  disconnect?: Prisma.EmpresaWhereUniqueInput | Prisma.EmpresaWhereUniqueInput[]
  delete?: Prisma.EmpresaWhereUniqueInput | Prisma.EmpresaWhereUniqueInput[]
  connect?: Prisma.EmpresaWhereUniqueInput | Prisma.EmpresaWhereUniqueInput[]
  update?: Prisma.EmpresaUpdateWithWhereUniqueWithoutUsuarioInput | Prisma.EmpresaUpdateWithWhereUniqueWithoutUsuarioInput[]
  updateMany?: Prisma.EmpresaUpdateManyWithWhereWithoutUsuarioInput | Prisma.EmpresaUpdateManyWithWhereWithoutUsuarioInput[]
  deleteMany?: Prisma.EmpresaScalarWhereInput | Prisma.EmpresaScalarWhereInput[]
}

export type EmpresaCreateNestedOneWithoutDepartamentosInput = {
  create?: Prisma.XOR<Prisma.EmpresaCreateWithoutDepartamentosInput, Prisma.EmpresaUncheckedCreateWithoutDepartamentosInput>
  connectOrCreate?: Prisma.EmpresaCreateOrConnectWithoutDepartamentosInput
  connect?: Prisma.EmpresaWhereUniqueInput
}

export type EmpresaUpdateOneRequiredWithoutDepartamentosNestedInput = {
  create?: Prisma.XOR<Prisma.EmpresaCreateWithoutDepartamentosInput, Prisma.EmpresaUncheckedCreateWithoutDepartamentosInput>
  connectOrCreate?: Prisma.EmpresaCreateOrConnectWithoutDepartamentosInput
  upsert?: Prisma.EmpresaUpsertWithoutDepartamentosInput
  connect?: Prisma.EmpresaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EmpresaUpdateToOneWithWhereWithoutDepartamentosInput, Prisma.EmpresaUpdateWithoutDepartamentosInput>, Prisma.EmpresaUncheckedUpdateWithoutDepartamentosInput>
}

export type EmpresaCreateNestedOneWithoutBots_alocadosInput = {
  create?: Prisma.XOR<Prisma.EmpresaCreateWithoutBots_alocadosInput, Prisma.EmpresaUncheckedCreateWithoutBots_alocadosInput>
  connectOrCreate?: Prisma.EmpresaCreateOrConnectWithoutBots_alocadosInput
  connect?: Prisma.EmpresaWhereUniqueInput
}

export type EmpresaUpdateOneRequiredWithoutBots_alocadosNestedInput = {
  create?: Prisma.XOR<Prisma.EmpresaCreateWithoutBots_alocadosInput, Prisma.EmpresaUncheckedCreateWithoutBots_alocadosInput>
  connectOrCreate?: Prisma.EmpresaCreateOrConnectWithoutBots_alocadosInput
  upsert?: Prisma.EmpresaUpsertWithoutBots_alocadosInput
  connect?: Prisma.EmpresaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EmpresaUpdateToOneWithWhereWithoutBots_alocadosInput, Prisma.EmpresaUpdateWithoutBots_alocadosInput>, Prisma.EmpresaUncheckedUpdateWithoutBots_alocadosInput>
}

export type EmpresaCreateNestedOneWithoutTransacoesInput = {
  create?: Prisma.XOR<Prisma.EmpresaCreateWithoutTransacoesInput, Prisma.EmpresaUncheckedCreateWithoutTransacoesInput>
  connectOrCreate?: Prisma.EmpresaCreateOrConnectWithoutTransacoesInput
  connect?: Prisma.EmpresaWhereUniqueInput
}

export type EmpresaUpdateOneRequiredWithoutTransacoesNestedInput = {
  create?: Prisma.XOR<Prisma.EmpresaCreateWithoutTransacoesInput, Prisma.EmpresaUncheckedCreateWithoutTransacoesInput>
  connectOrCreate?: Prisma.EmpresaCreateOrConnectWithoutTransacoesInput
  upsert?: Prisma.EmpresaUpsertWithoutTransacoesInput
  connect?: Prisma.EmpresaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EmpresaUpdateToOneWithWhereWithoutTransacoesInput, Prisma.EmpresaUpdateWithoutTransacoesInput>, Prisma.EmpresaUncheckedUpdateWithoutTransacoesInput>
}

export type EmpresaCreateNestedOneWithoutArquivosInput = {
  create?: Prisma.XOR<Prisma.EmpresaCreateWithoutArquivosInput, Prisma.EmpresaUncheckedCreateWithoutArquivosInput>
  connectOrCreate?: Prisma.EmpresaCreateOrConnectWithoutArquivosInput
  connect?: Prisma.EmpresaWhereUniqueInput
}

export type EmpresaUpdateOneRequiredWithoutArquivosNestedInput = {
  create?: Prisma.XOR<Prisma.EmpresaCreateWithoutArquivosInput, Prisma.EmpresaUncheckedCreateWithoutArquivosInput>
  connectOrCreate?: Prisma.EmpresaCreateOrConnectWithoutArquivosInput
  upsert?: Prisma.EmpresaUpsertWithoutArquivosInput
  connect?: Prisma.EmpresaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EmpresaUpdateToOneWithWhereWithoutArquivosInput, Prisma.EmpresaUpdateWithoutArquivosInput>, Prisma.EmpresaUncheckedUpdateWithoutArquivosInput>
}

export type EmpresaCreateWithoutUsuarioInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
  departamentos?: Prisma.DepartamentoCreateNestedManyWithoutEmpresaInput
  transacoes?: Prisma.TransacaoCreateNestedManyWithoutEmpresaInput
  arquivos?: Prisma.ArquivoCreateNestedManyWithoutEmpresaInput
  bots_alocados?: Prisma.BotEmpresaCreateNestedManyWithoutEmpresaInput
}

export type EmpresaUncheckedCreateWithoutUsuarioInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
  departamentos?: Prisma.DepartamentoUncheckedCreateNestedManyWithoutEmpresaInput
  transacoes?: Prisma.TransacaoUncheckedCreateNestedManyWithoutEmpresaInput
  arquivos?: Prisma.ArquivoUncheckedCreateNestedManyWithoutEmpresaInput
  bots_alocados?: Prisma.BotEmpresaUncheckedCreateNestedManyWithoutEmpresaInput
}

export type EmpresaCreateOrConnectWithoutUsuarioInput = {
  where: Prisma.EmpresaWhereUniqueInput
  create: Prisma.XOR<Prisma.EmpresaCreateWithoutUsuarioInput, Prisma.EmpresaUncheckedCreateWithoutUsuarioInput>
}

export type EmpresaCreateManyUsuarioInputEnvelope = {
  data: Prisma.EmpresaCreateManyUsuarioInput | Prisma.EmpresaCreateManyUsuarioInput[]
  skipDuplicates?: boolean
}

export type EmpresaUpsertWithWhereUniqueWithoutUsuarioInput = {
  where: Prisma.EmpresaWhereUniqueInput
  update: Prisma.XOR<Prisma.EmpresaUpdateWithoutUsuarioInput, Prisma.EmpresaUncheckedUpdateWithoutUsuarioInput>
  create: Prisma.XOR<Prisma.EmpresaCreateWithoutUsuarioInput, Prisma.EmpresaUncheckedCreateWithoutUsuarioInput>
}

export type EmpresaUpdateWithWhereUniqueWithoutUsuarioInput = {
  where: Prisma.EmpresaWhereUniqueInput
  data: Prisma.XOR<Prisma.EmpresaUpdateWithoutUsuarioInput, Prisma.EmpresaUncheckedUpdateWithoutUsuarioInput>
}

export type EmpresaUpdateManyWithWhereWithoutUsuarioInput = {
  where: Prisma.EmpresaScalarWhereInput
  data: Prisma.XOR<Prisma.EmpresaUpdateManyMutationInput, Prisma.EmpresaUncheckedUpdateManyWithoutUsuarioInput>
}

export type EmpresaScalarWhereInput = {
  AND?: Prisma.EmpresaScalarWhereInput | Prisma.EmpresaScalarWhereInput[]
  OR?: Prisma.EmpresaScalarWhereInput[]
  NOT?: Prisma.EmpresaScalarWhereInput | Prisma.EmpresaScalarWhereInput[]
  id?: Prisma.StringFilter<"Empresa"> | string
  nome?: Prisma.StringFilter<"Empresa"> | string
  sector?: Prisma.StringFilter<"Empresa"> | string
  website?: Prisma.StringNullableFilter<"Empresa"> | string | null
  logotipo?: Prisma.StringNullableFilter<"Empresa"> | string | null
  cor_primaria?: Prisma.StringNullableFilter<"Empresa"> | string | null
  created_at?: Prisma.DateTimeFilter<"Empresa"> | Date | string
  usuarioId?: Prisma.StringFilter<"Empresa"> | string
}

export type EmpresaCreateWithoutDepartamentosInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutEmpresasInput
  transacoes?: Prisma.TransacaoCreateNestedManyWithoutEmpresaInput
  arquivos?: Prisma.ArquivoCreateNestedManyWithoutEmpresaInput
  bots_alocados?: Prisma.BotEmpresaCreateNestedManyWithoutEmpresaInput
}

export type EmpresaUncheckedCreateWithoutDepartamentosInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
  usuarioId: string
  transacoes?: Prisma.TransacaoUncheckedCreateNestedManyWithoutEmpresaInput
  arquivos?: Prisma.ArquivoUncheckedCreateNestedManyWithoutEmpresaInput
  bots_alocados?: Prisma.BotEmpresaUncheckedCreateNestedManyWithoutEmpresaInput
}

export type EmpresaCreateOrConnectWithoutDepartamentosInput = {
  where: Prisma.EmpresaWhereUniqueInput
  create: Prisma.XOR<Prisma.EmpresaCreateWithoutDepartamentosInput, Prisma.EmpresaUncheckedCreateWithoutDepartamentosInput>
}

export type EmpresaUpsertWithoutDepartamentosInput = {
  update: Prisma.XOR<Prisma.EmpresaUpdateWithoutDepartamentosInput, Prisma.EmpresaUncheckedUpdateWithoutDepartamentosInput>
  create: Prisma.XOR<Prisma.EmpresaCreateWithoutDepartamentosInput, Prisma.EmpresaUncheckedCreateWithoutDepartamentosInput>
  where?: Prisma.EmpresaWhereInput
}

export type EmpresaUpdateToOneWithWhereWithoutDepartamentosInput = {
  where?: Prisma.EmpresaWhereInput
  data: Prisma.XOR<Prisma.EmpresaUpdateWithoutDepartamentosInput, Prisma.EmpresaUncheckedUpdateWithoutDepartamentosInput>
}

export type EmpresaUpdateWithoutDepartamentosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutEmpresasNestedInput
  transacoes?: Prisma.TransacaoUpdateManyWithoutEmpresaNestedInput
  arquivos?: Prisma.ArquivoUpdateManyWithoutEmpresaNestedInput
  bots_alocados?: Prisma.BotEmpresaUpdateManyWithoutEmpresaNestedInput
}

export type EmpresaUncheckedUpdateWithoutDepartamentosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  transacoes?: Prisma.TransacaoUncheckedUpdateManyWithoutEmpresaNestedInput
  arquivos?: Prisma.ArquivoUncheckedUpdateManyWithoutEmpresaNestedInput
  bots_alocados?: Prisma.BotEmpresaUncheckedUpdateManyWithoutEmpresaNestedInput
}

export type EmpresaCreateWithoutBots_alocadosInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutEmpresasInput
  departamentos?: Prisma.DepartamentoCreateNestedManyWithoutEmpresaInput
  transacoes?: Prisma.TransacaoCreateNestedManyWithoutEmpresaInput
  arquivos?: Prisma.ArquivoCreateNestedManyWithoutEmpresaInput
}

export type EmpresaUncheckedCreateWithoutBots_alocadosInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
  usuarioId: string
  departamentos?: Prisma.DepartamentoUncheckedCreateNestedManyWithoutEmpresaInput
  transacoes?: Prisma.TransacaoUncheckedCreateNestedManyWithoutEmpresaInput
  arquivos?: Prisma.ArquivoUncheckedCreateNestedManyWithoutEmpresaInput
}

export type EmpresaCreateOrConnectWithoutBots_alocadosInput = {
  where: Prisma.EmpresaWhereUniqueInput
  create: Prisma.XOR<Prisma.EmpresaCreateWithoutBots_alocadosInput, Prisma.EmpresaUncheckedCreateWithoutBots_alocadosInput>
}

export type EmpresaUpsertWithoutBots_alocadosInput = {
  update: Prisma.XOR<Prisma.EmpresaUpdateWithoutBots_alocadosInput, Prisma.EmpresaUncheckedUpdateWithoutBots_alocadosInput>
  create: Prisma.XOR<Prisma.EmpresaCreateWithoutBots_alocadosInput, Prisma.EmpresaUncheckedCreateWithoutBots_alocadosInput>
  where?: Prisma.EmpresaWhereInput
}

export type EmpresaUpdateToOneWithWhereWithoutBots_alocadosInput = {
  where?: Prisma.EmpresaWhereInput
  data: Prisma.XOR<Prisma.EmpresaUpdateWithoutBots_alocadosInput, Prisma.EmpresaUncheckedUpdateWithoutBots_alocadosInput>
}

export type EmpresaUpdateWithoutBots_alocadosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutEmpresasNestedInput
  departamentos?: Prisma.DepartamentoUpdateManyWithoutEmpresaNestedInput
  transacoes?: Prisma.TransacaoUpdateManyWithoutEmpresaNestedInput
  arquivos?: Prisma.ArquivoUpdateManyWithoutEmpresaNestedInput
}

export type EmpresaUncheckedUpdateWithoutBots_alocadosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  departamentos?: Prisma.DepartamentoUncheckedUpdateManyWithoutEmpresaNestedInput
  transacoes?: Prisma.TransacaoUncheckedUpdateManyWithoutEmpresaNestedInput
  arquivos?: Prisma.ArquivoUncheckedUpdateManyWithoutEmpresaNestedInput
}

export type EmpresaCreateWithoutTransacoesInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutEmpresasInput
  departamentos?: Prisma.DepartamentoCreateNestedManyWithoutEmpresaInput
  arquivos?: Prisma.ArquivoCreateNestedManyWithoutEmpresaInput
  bots_alocados?: Prisma.BotEmpresaCreateNestedManyWithoutEmpresaInput
}

export type EmpresaUncheckedCreateWithoutTransacoesInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
  usuarioId: string
  departamentos?: Prisma.DepartamentoUncheckedCreateNestedManyWithoutEmpresaInput
  arquivos?: Prisma.ArquivoUncheckedCreateNestedManyWithoutEmpresaInput
  bots_alocados?: Prisma.BotEmpresaUncheckedCreateNestedManyWithoutEmpresaInput
}

export type EmpresaCreateOrConnectWithoutTransacoesInput = {
  where: Prisma.EmpresaWhereUniqueInput
  create: Prisma.XOR<Prisma.EmpresaCreateWithoutTransacoesInput, Prisma.EmpresaUncheckedCreateWithoutTransacoesInput>
}

export type EmpresaUpsertWithoutTransacoesInput = {
  update: Prisma.XOR<Prisma.EmpresaUpdateWithoutTransacoesInput, Prisma.EmpresaUncheckedUpdateWithoutTransacoesInput>
  create: Prisma.XOR<Prisma.EmpresaCreateWithoutTransacoesInput, Prisma.EmpresaUncheckedCreateWithoutTransacoesInput>
  where?: Prisma.EmpresaWhereInput
}

export type EmpresaUpdateToOneWithWhereWithoutTransacoesInput = {
  where?: Prisma.EmpresaWhereInput
  data: Prisma.XOR<Prisma.EmpresaUpdateWithoutTransacoesInput, Prisma.EmpresaUncheckedUpdateWithoutTransacoesInput>
}

export type EmpresaUpdateWithoutTransacoesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutEmpresasNestedInput
  departamentos?: Prisma.DepartamentoUpdateManyWithoutEmpresaNestedInput
  arquivos?: Prisma.ArquivoUpdateManyWithoutEmpresaNestedInput
  bots_alocados?: Prisma.BotEmpresaUpdateManyWithoutEmpresaNestedInput
}

export type EmpresaUncheckedUpdateWithoutTransacoesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  departamentos?: Prisma.DepartamentoUncheckedUpdateManyWithoutEmpresaNestedInput
  arquivos?: Prisma.ArquivoUncheckedUpdateManyWithoutEmpresaNestedInput
  bots_alocados?: Prisma.BotEmpresaUncheckedUpdateManyWithoutEmpresaNestedInput
}

export type EmpresaCreateWithoutArquivosInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
  usuario: Prisma.UsuarioCreateNestedOneWithoutEmpresasInput
  departamentos?: Prisma.DepartamentoCreateNestedManyWithoutEmpresaInput
  transacoes?: Prisma.TransacaoCreateNestedManyWithoutEmpresaInput
  bots_alocados?: Prisma.BotEmpresaCreateNestedManyWithoutEmpresaInput
}

export type EmpresaUncheckedCreateWithoutArquivosInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
  usuarioId: string
  departamentos?: Prisma.DepartamentoUncheckedCreateNestedManyWithoutEmpresaInput
  transacoes?: Prisma.TransacaoUncheckedCreateNestedManyWithoutEmpresaInput
  bots_alocados?: Prisma.BotEmpresaUncheckedCreateNestedManyWithoutEmpresaInput
}

export type EmpresaCreateOrConnectWithoutArquivosInput = {
  where: Prisma.EmpresaWhereUniqueInput
  create: Prisma.XOR<Prisma.EmpresaCreateWithoutArquivosInput, Prisma.EmpresaUncheckedCreateWithoutArquivosInput>
}

export type EmpresaUpsertWithoutArquivosInput = {
  update: Prisma.XOR<Prisma.EmpresaUpdateWithoutArquivosInput, Prisma.EmpresaUncheckedUpdateWithoutArquivosInput>
  create: Prisma.XOR<Prisma.EmpresaCreateWithoutArquivosInput, Prisma.EmpresaUncheckedCreateWithoutArquivosInput>
  where?: Prisma.EmpresaWhereInput
}

export type EmpresaUpdateToOneWithWhereWithoutArquivosInput = {
  where?: Prisma.EmpresaWhereInput
  data: Prisma.XOR<Prisma.EmpresaUpdateWithoutArquivosInput, Prisma.EmpresaUncheckedUpdateWithoutArquivosInput>
}

export type EmpresaUpdateWithoutArquivosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuario?: Prisma.UsuarioUpdateOneRequiredWithoutEmpresasNestedInput
  departamentos?: Prisma.DepartamentoUpdateManyWithoutEmpresaNestedInput
  transacoes?: Prisma.TransacaoUpdateManyWithoutEmpresaNestedInput
  bots_alocados?: Prisma.BotEmpresaUpdateManyWithoutEmpresaNestedInput
}

export type EmpresaUncheckedUpdateWithoutArquivosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  usuarioId?: Prisma.StringFieldUpdateOperationsInput | string
  departamentos?: Prisma.DepartamentoUncheckedUpdateManyWithoutEmpresaNestedInput
  transacoes?: Prisma.TransacaoUncheckedUpdateManyWithoutEmpresaNestedInput
  bots_alocados?: Prisma.BotEmpresaUncheckedUpdateManyWithoutEmpresaNestedInput
}

export type EmpresaCreateManyUsuarioInput = {
  id?: string
  nome: string
  sector: string
  website?: string | null
  logotipo?: string | null
  cor_primaria?: string | null
  created_at?: Date | string
}

export type EmpresaUpdateWithoutUsuarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departamentos?: Prisma.DepartamentoUpdateManyWithoutEmpresaNestedInput
  transacoes?: Prisma.TransacaoUpdateManyWithoutEmpresaNestedInput
  arquivos?: Prisma.ArquivoUpdateManyWithoutEmpresaNestedInput
  bots_alocados?: Prisma.BotEmpresaUpdateManyWithoutEmpresaNestedInput
}

export type EmpresaUncheckedUpdateWithoutUsuarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  departamentos?: Prisma.DepartamentoUncheckedUpdateManyWithoutEmpresaNestedInput
  transacoes?: Prisma.TransacaoUncheckedUpdateManyWithoutEmpresaNestedInput
  arquivos?: Prisma.ArquivoUncheckedUpdateManyWithoutEmpresaNestedInput
  bots_alocados?: Prisma.BotEmpresaUncheckedUpdateManyWithoutEmpresaNestedInput
}

export type EmpresaUncheckedUpdateManyWithoutUsuarioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sector?: Prisma.StringFieldUpdateOperationsInput | string
  website?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logotipo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cor_primaria?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type EmpresaCountOutputType
 */

export type EmpresaCountOutputType = {
  departamentos: number
  transacoes: number
  arquivos: number
  bots_alocados: number
}

export type EmpresaCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  departamentos?: boolean | EmpresaCountOutputTypeCountDepartamentosArgs
  transacoes?: boolean | EmpresaCountOutputTypeCountTransacoesArgs
  arquivos?: boolean | EmpresaCountOutputTypeCountArquivosArgs
  bots_alocados?: boolean | EmpresaCountOutputTypeCountBots_alocadosArgs
}

/**
 * EmpresaCountOutputType without action
 */
export type EmpresaCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmpresaCountOutputType
   */
  select?: Prisma.EmpresaCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EmpresaCountOutputType without action
 */
export type EmpresaCountOutputTypeCountDepartamentosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DepartamentoWhereInput
}

/**
 * EmpresaCountOutputType without action
 */
export type EmpresaCountOutputTypeCountTransacoesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransacaoWhereInput
}

/**
 * EmpresaCountOutputType without action
 */
export type EmpresaCountOutputTypeCountArquivosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ArquivoWhereInput
}

/**
 * EmpresaCountOutputType without action
 */
export type EmpresaCountOutputTypeCountBots_alocadosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BotEmpresaWhereInput
}


export type EmpresaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  sector?: boolean
  website?: boolean
  logotipo?: boolean
  cor_primaria?: boolean
  created_at?: boolean
  usuarioId?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  departamentos?: boolean | Prisma.Empresa$departamentosArgs<ExtArgs>
  transacoes?: boolean | Prisma.Empresa$transacoesArgs<ExtArgs>
  arquivos?: boolean | Prisma.Empresa$arquivosArgs<ExtArgs>
  bots_alocados?: boolean | Prisma.Empresa$bots_alocadosArgs<ExtArgs>
  _count?: boolean | Prisma.EmpresaCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["empresa"]>

export type EmpresaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  sector?: boolean
  website?: boolean
  logotipo?: boolean
  cor_primaria?: boolean
  created_at?: boolean
  usuarioId?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}, ExtArgs["result"]["empresa"]>

export type EmpresaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  sector?: boolean
  website?: boolean
  logotipo?: boolean
  cor_primaria?: boolean
  created_at?: boolean
  usuarioId?: boolean
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}, ExtArgs["result"]["empresa"]>

export type EmpresaSelectScalar = {
  id?: boolean
  nome?: boolean
  sector?: boolean
  website?: boolean
  logotipo?: boolean
  cor_primaria?: boolean
  created_at?: boolean
  usuarioId?: boolean
}

export type EmpresaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nome" | "sector" | "website" | "logotipo" | "cor_primaria" | "created_at" | "usuarioId", ExtArgs["result"]["empresa"]>
export type EmpresaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
  departamentos?: boolean | Prisma.Empresa$departamentosArgs<ExtArgs>
  transacoes?: boolean | Prisma.Empresa$transacoesArgs<ExtArgs>
  arquivos?: boolean | Prisma.Empresa$arquivosArgs<ExtArgs>
  bots_alocados?: boolean | Prisma.Empresa$bots_alocadosArgs<ExtArgs>
  _count?: boolean | Prisma.EmpresaCountOutputTypeDefaultArgs<ExtArgs>
}
export type EmpresaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}
export type EmpresaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuarioDefaultArgs<ExtArgs>
}

export type $EmpresaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Empresa"
  objects: {
    usuario: Prisma.$UsuarioPayload<ExtArgs>
    departamentos: Prisma.$DepartamentoPayload<ExtArgs>[]
    transacoes: Prisma.$TransacaoPayload<ExtArgs>[]
    arquivos: Prisma.$ArquivoPayload<ExtArgs>[]
    bots_alocados: Prisma.$BotEmpresaPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    nome: string
    sector: string
    website: string | null
    logotipo: string | null
    cor_primaria: string | null
    created_at: Date
    usuarioId: string
  }, ExtArgs["result"]["empresa"]>
  composites: {}
}

export type EmpresaGetPayload<S extends boolean | null | undefined | EmpresaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EmpresaPayload, S>

export type EmpresaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EmpresaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmpresaCountAggregateInputType | true
  }

export interface EmpresaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Empresa'], meta: { name: 'Empresa' } }
  /**
   * Find zero or one Empresa that matches the filter.
   * @param {EmpresaFindUniqueArgs} args - Arguments to find a Empresa
   * @example
   * // Get one Empresa
   * const empresa = await prisma.empresa.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EmpresaFindUniqueArgs>(args: Prisma.SelectSubset<T, EmpresaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EmpresaClient<runtime.Types.Result.GetResult<Prisma.$EmpresaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Empresa that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EmpresaFindUniqueOrThrowArgs} args - Arguments to find a Empresa
   * @example
   * // Get one Empresa
   * const empresa = await prisma.empresa.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EmpresaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EmpresaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmpresaClient<runtime.Types.Result.GetResult<Prisma.$EmpresaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Empresa that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresaFindFirstArgs} args - Arguments to find a Empresa
   * @example
   * // Get one Empresa
   * const empresa = await prisma.empresa.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EmpresaFindFirstArgs>(args?: Prisma.SelectSubset<T, EmpresaFindFirstArgs<ExtArgs>>): Prisma.Prisma__EmpresaClient<runtime.Types.Result.GetResult<Prisma.$EmpresaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Empresa that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresaFindFirstOrThrowArgs} args - Arguments to find a Empresa
   * @example
   * // Get one Empresa
   * const empresa = await prisma.empresa.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EmpresaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EmpresaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmpresaClient<runtime.Types.Result.GetResult<Prisma.$EmpresaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Empresas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Empresas
   * const empresas = await prisma.empresa.findMany()
   * 
   * // Get first 10 Empresas
   * const empresas = await prisma.empresa.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const empresaWithIdOnly = await prisma.empresa.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EmpresaFindManyArgs>(args?: Prisma.SelectSubset<T, EmpresaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmpresaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Empresa.
   * @param {EmpresaCreateArgs} args - Arguments to create a Empresa.
   * @example
   * // Create one Empresa
   * const Empresa = await prisma.empresa.create({
   *   data: {
   *     // ... data to create a Empresa
   *   }
   * })
   * 
   */
  create<T extends EmpresaCreateArgs>(args: Prisma.SelectSubset<T, EmpresaCreateArgs<ExtArgs>>): Prisma.Prisma__EmpresaClient<runtime.Types.Result.GetResult<Prisma.$EmpresaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Empresas.
   * @param {EmpresaCreateManyArgs} args - Arguments to create many Empresas.
   * @example
   * // Create many Empresas
   * const empresa = await prisma.empresa.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EmpresaCreateManyArgs>(args?: Prisma.SelectSubset<T, EmpresaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Empresas and returns the data saved in the database.
   * @param {EmpresaCreateManyAndReturnArgs} args - Arguments to create many Empresas.
   * @example
   * // Create many Empresas
   * const empresa = await prisma.empresa.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Empresas and only return the `id`
   * const empresaWithIdOnly = await prisma.empresa.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EmpresaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EmpresaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmpresaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Empresa.
   * @param {EmpresaDeleteArgs} args - Arguments to delete one Empresa.
   * @example
   * // Delete one Empresa
   * const Empresa = await prisma.empresa.delete({
   *   where: {
   *     // ... filter to delete one Empresa
   *   }
   * })
   * 
   */
  delete<T extends EmpresaDeleteArgs>(args: Prisma.SelectSubset<T, EmpresaDeleteArgs<ExtArgs>>): Prisma.Prisma__EmpresaClient<runtime.Types.Result.GetResult<Prisma.$EmpresaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Empresa.
   * @param {EmpresaUpdateArgs} args - Arguments to update one Empresa.
   * @example
   * // Update one Empresa
   * const empresa = await prisma.empresa.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EmpresaUpdateArgs>(args: Prisma.SelectSubset<T, EmpresaUpdateArgs<ExtArgs>>): Prisma.Prisma__EmpresaClient<runtime.Types.Result.GetResult<Prisma.$EmpresaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Empresas.
   * @param {EmpresaDeleteManyArgs} args - Arguments to filter Empresas to delete.
   * @example
   * // Delete a few Empresas
   * const { count } = await prisma.empresa.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EmpresaDeleteManyArgs>(args?: Prisma.SelectSubset<T, EmpresaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Empresas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Empresas
   * const empresa = await prisma.empresa.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EmpresaUpdateManyArgs>(args: Prisma.SelectSubset<T, EmpresaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Empresas and returns the data updated in the database.
   * @param {EmpresaUpdateManyAndReturnArgs} args - Arguments to update many Empresas.
   * @example
   * // Update many Empresas
   * const empresa = await prisma.empresa.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Empresas and only return the `id`
   * const empresaWithIdOnly = await prisma.empresa.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EmpresaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EmpresaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmpresaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Empresa.
   * @param {EmpresaUpsertArgs} args - Arguments to update or create a Empresa.
   * @example
   * // Update or create a Empresa
   * const empresa = await prisma.empresa.upsert({
   *   create: {
   *     // ... data to create a Empresa
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Empresa we want to update
   *   }
   * })
   */
  upsert<T extends EmpresaUpsertArgs>(args: Prisma.SelectSubset<T, EmpresaUpsertArgs<ExtArgs>>): Prisma.Prisma__EmpresaClient<runtime.Types.Result.GetResult<Prisma.$EmpresaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Empresas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresaCountArgs} args - Arguments to filter Empresas to count.
   * @example
   * // Count the number of Empresas
   * const count = await prisma.empresa.count({
   *   where: {
   *     // ... the filter for the Empresas we want to count
   *   }
   * })
  **/
  count<T extends EmpresaCountArgs>(
    args?: Prisma.Subset<T, EmpresaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmpresaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Empresa.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmpresaAggregateArgs>(args: Prisma.Subset<T, EmpresaAggregateArgs>): Prisma.PrismaPromise<GetEmpresaAggregateType<T>>

  /**
   * Group by Empresa.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EmpresaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EmpresaGroupByArgs['orderBy'] }
      : { orderBy?: EmpresaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EmpresaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmpresaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Empresa model
 */
readonly fields: EmpresaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Empresa.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EmpresaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  usuario<T extends Prisma.UsuarioDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsuarioDefaultArgs<ExtArgs>>): Prisma.Prisma__UsuarioClient<runtime.Types.Result.GetResult<Prisma.$UsuarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  departamentos<T extends Prisma.Empresa$departamentosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Empresa$departamentosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DepartamentoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  transacoes<T extends Prisma.Empresa$transacoesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Empresa$transacoesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransacaoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  arquivos<T extends Prisma.Empresa$arquivosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Empresa$arquivosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArquivoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  bots_alocados<T extends Prisma.Empresa$bots_alocadosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Empresa$bots_alocadosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BotEmpresaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Empresa model
 */
export interface EmpresaFieldRefs {
  readonly id: Prisma.FieldRef<"Empresa", 'String'>
  readonly nome: Prisma.FieldRef<"Empresa", 'String'>
  readonly sector: Prisma.FieldRef<"Empresa", 'String'>
  readonly website: Prisma.FieldRef<"Empresa", 'String'>
  readonly logotipo: Prisma.FieldRef<"Empresa", 'String'>
  readonly cor_primaria: Prisma.FieldRef<"Empresa", 'String'>
  readonly created_at: Prisma.FieldRef<"Empresa", 'DateTime'>
  readonly usuarioId: Prisma.FieldRef<"Empresa", 'String'>
}
    

// Custom InputTypes
/**
 * Empresa findUnique
 */
export type EmpresaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresa
   */
  select?: Prisma.EmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresa
   */
  omit?: Prisma.EmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmpresaInclude<ExtArgs> | null
  /**
   * Filter, which Empresa to fetch.
   */
  where: Prisma.EmpresaWhereUniqueInput
}

/**
 * Empresa findUniqueOrThrow
 */
export type EmpresaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresa
   */
  select?: Prisma.EmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresa
   */
  omit?: Prisma.EmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmpresaInclude<ExtArgs> | null
  /**
   * Filter, which Empresa to fetch.
   */
  where: Prisma.EmpresaWhereUniqueInput
}

/**
 * Empresa findFirst
 */
export type EmpresaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresa
   */
  select?: Prisma.EmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresa
   */
  omit?: Prisma.EmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmpresaInclude<ExtArgs> | null
  /**
   * Filter, which Empresa to fetch.
   */
  where?: Prisma.EmpresaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Empresas to fetch.
   */
  orderBy?: Prisma.EmpresaOrderByWithRelationInput | Prisma.EmpresaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Empresas.
   */
  cursor?: Prisma.EmpresaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Empresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Empresas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Empresas.
   */
  distinct?: Prisma.EmpresaScalarFieldEnum | Prisma.EmpresaScalarFieldEnum[]
}

/**
 * Empresa findFirstOrThrow
 */
export type EmpresaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresa
   */
  select?: Prisma.EmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresa
   */
  omit?: Prisma.EmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmpresaInclude<ExtArgs> | null
  /**
   * Filter, which Empresa to fetch.
   */
  where?: Prisma.EmpresaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Empresas to fetch.
   */
  orderBy?: Prisma.EmpresaOrderByWithRelationInput | Prisma.EmpresaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Empresas.
   */
  cursor?: Prisma.EmpresaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Empresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Empresas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Empresas.
   */
  distinct?: Prisma.EmpresaScalarFieldEnum | Prisma.EmpresaScalarFieldEnum[]
}

/**
 * Empresa findMany
 */
export type EmpresaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresa
   */
  select?: Prisma.EmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresa
   */
  omit?: Prisma.EmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmpresaInclude<ExtArgs> | null
  /**
   * Filter, which Empresas to fetch.
   */
  where?: Prisma.EmpresaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Empresas to fetch.
   */
  orderBy?: Prisma.EmpresaOrderByWithRelationInput | Prisma.EmpresaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Empresas.
   */
  cursor?: Prisma.EmpresaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Empresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Empresas.
   */
  skip?: number
  distinct?: Prisma.EmpresaScalarFieldEnum | Prisma.EmpresaScalarFieldEnum[]
}

/**
 * Empresa create
 */
export type EmpresaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresa
   */
  select?: Prisma.EmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresa
   */
  omit?: Prisma.EmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmpresaInclude<ExtArgs> | null
  /**
   * The data needed to create a Empresa.
   */
  data: Prisma.XOR<Prisma.EmpresaCreateInput, Prisma.EmpresaUncheckedCreateInput>
}

/**
 * Empresa createMany
 */
export type EmpresaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Empresas.
   */
  data: Prisma.EmpresaCreateManyInput | Prisma.EmpresaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Empresa createManyAndReturn
 */
export type EmpresaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresa
   */
  select?: Prisma.EmpresaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Empresa
   */
  omit?: Prisma.EmpresaOmit<ExtArgs> | null
  /**
   * The data used to create many Empresas.
   */
  data: Prisma.EmpresaCreateManyInput | Prisma.EmpresaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmpresaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Empresa update
 */
export type EmpresaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresa
   */
  select?: Prisma.EmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresa
   */
  omit?: Prisma.EmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmpresaInclude<ExtArgs> | null
  /**
   * The data needed to update a Empresa.
   */
  data: Prisma.XOR<Prisma.EmpresaUpdateInput, Prisma.EmpresaUncheckedUpdateInput>
  /**
   * Choose, which Empresa to update.
   */
  where: Prisma.EmpresaWhereUniqueInput
}

/**
 * Empresa updateMany
 */
export type EmpresaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Empresas.
   */
  data: Prisma.XOR<Prisma.EmpresaUpdateManyMutationInput, Prisma.EmpresaUncheckedUpdateManyInput>
  /**
   * Filter which Empresas to update
   */
  where?: Prisma.EmpresaWhereInput
  /**
   * Limit how many Empresas to update.
   */
  limit?: number
}

/**
 * Empresa updateManyAndReturn
 */
export type EmpresaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresa
   */
  select?: Prisma.EmpresaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Empresa
   */
  omit?: Prisma.EmpresaOmit<ExtArgs> | null
  /**
   * The data used to update Empresas.
   */
  data: Prisma.XOR<Prisma.EmpresaUpdateManyMutationInput, Prisma.EmpresaUncheckedUpdateManyInput>
  /**
   * Filter which Empresas to update
   */
  where?: Prisma.EmpresaWhereInput
  /**
   * Limit how many Empresas to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmpresaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Empresa upsert
 */
export type EmpresaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresa
   */
  select?: Prisma.EmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresa
   */
  omit?: Prisma.EmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmpresaInclude<ExtArgs> | null
  /**
   * The filter to search for the Empresa to update in case it exists.
   */
  where: Prisma.EmpresaWhereUniqueInput
  /**
   * In case the Empresa found by the `where` argument doesn't exist, create a new Empresa with this data.
   */
  create: Prisma.XOR<Prisma.EmpresaCreateInput, Prisma.EmpresaUncheckedCreateInput>
  /**
   * In case the Empresa was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EmpresaUpdateInput, Prisma.EmpresaUncheckedUpdateInput>
}

/**
 * Empresa delete
 */
export type EmpresaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresa
   */
  select?: Prisma.EmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresa
   */
  omit?: Prisma.EmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmpresaInclude<ExtArgs> | null
  /**
   * Filter which Empresa to delete.
   */
  where: Prisma.EmpresaWhereUniqueInput
}

/**
 * Empresa deleteMany
 */
export type EmpresaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Empresas to delete
   */
  where?: Prisma.EmpresaWhereInput
  /**
   * Limit how many Empresas to delete.
   */
  limit?: number
}

/**
 * Empresa.departamentos
 */
export type Empresa$departamentosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Departamento
   */
  select?: Prisma.DepartamentoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Departamento
   */
  omit?: Prisma.DepartamentoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DepartamentoInclude<ExtArgs> | null
  where?: Prisma.DepartamentoWhereInput
  orderBy?: Prisma.DepartamentoOrderByWithRelationInput | Prisma.DepartamentoOrderByWithRelationInput[]
  cursor?: Prisma.DepartamentoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DepartamentoScalarFieldEnum | Prisma.DepartamentoScalarFieldEnum[]
}

/**
 * Empresa.transacoes
 */
export type Empresa$transacoesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transacao
   */
  select?: Prisma.TransacaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transacao
   */
  omit?: Prisma.TransacaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransacaoInclude<ExtArgs> | null
  where?: Prisma.TransacaoWhereInput
  orderBy?: Prisma.TransacaoOrderByWithRelationInput | Prisma.TransacaoOrderByWithRelationInput[]
  cursor?: Prisma.TransacaoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TransacaoScalarFieldEnum | Prisma.TransacaoScalarFieldEnum[]
}

/**
 * Empresa.arquivos
 */
export type Empresa$arquivosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Arquivo
   */
  select?: Prisma.ArquivoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Arquivo
   */
  omit?: Prisma.ArquivoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArquivoInclude<ExtArgs> | null
  where?: Prisma.ArquivoWhereInput
  orderBy?: Prisma.ArquivoOrderByWithRelationInput | Prisma.ArquivoOrderByWithRelationInput[]
  cursor?: Prisma.ArquivoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ArquivoScalarFieldEnum | Prisma.ArquivoScalarFieldEnum[]
}

/**
 * Empresa.bots_alocados
 */
export type Empresa$bots_alocadosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BotEmpresa
   */
  select?: Prisma.BotEmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BotEmpresa
   */
  omit?: Prisma.BotEmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BotEmpresaInclude<ExtArgs> | null
  where?: Prisma.BotEmpresaWhereInput
  orderBy?: Prisma.BotEmpresaOrderByWithRelationInput | Prisma.BotEmpresaOrderByWithRelationInput[]
  cursor?: Prisma.BotEmpresaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BotEmpresaScalarFieldEnum | Prisma.BotEmpresaScalarFieldEnum[]
}

/**
 * Empresa without action
 */
export type EmpresaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresa
   */
  select?: Prisma.EmpresaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresa
   */
  omit?: Prisma.EmpresaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmpresaInclude<ExtArgs> | null
}
