
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/library"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
 * Metrics
 */
export type Metrics = runtime.Metrics
export type Metric<T> = runtime.Metric<T>
export type MetricHistogram = runtime.MetricHistogram
export type MetricHistogramBucket = runtime.MetricHistogramBucket

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
export const prismaVersion: PrismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Usuario: 'Usuario',
  Empresa: 'Empresa',
  Departamento: 'Departamento',
  Bot: 'Bot',
  BotAsset: 'BotAsset',
  BotEmpresa: 'BotEmpresa',
  FolhaBot: 'FolhaBot',
  Transacao: 'Transacao',
  Arquivo: 'Arquivo',
  Notificacao: 'Notificacao'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "usuario" | "empresa" | "departamento" | "bot" | "botAsset" | "botEmpresa" | "folhaBot" | "transacao" | "arquivo" | "notificacao"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Usuario: {
      payload: Prisma.$UsuarioPayload<ExtArgs>
      fields: Prisma.UsuarioFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UsuarioFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuarioPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UsuarioFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuarioPayload>
        }
        findFirst: {
          args: Prisma.UsuarioFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuarioPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UsuarioFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuarioPayload>
        }
        findMany: {
          args: Prisma.UsuarioFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuarioPayload>[]
        }
        create: {
          args: Prisma.UsuarioCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuarioPayload>
        }
        createMany: {
          args: Prisma.UsuarioCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UsuarioCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuarioPayload>[]
        }
        delete: {
          args: Prisma.UsuarioDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuarioPayload>
        }
        update: {
          args: Prisma.UsuarioUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuarioPayload>
        }
        deleteMany: {
          args: Prisma.UsuarioDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UsuarioUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UsuarioUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuarioPayload>[]
        }
        upsert: {
          args: Prisma.UsuarioUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuarioPayload>
        }
        aggregate: {
          args: Prisma.UsuarioAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUsuario>
        }
        groupBy: {
          args: Prisma.UsuarioGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsuarioGroupByOutputType>[]
        }
        count: {
          args: Prisma.UsuarioCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsuarioCountAggregateOutputType> | number
        }
      }
    }
    Empresa: {
      payload: Prisma.$EmpresaPayload<ExtArgs>
      fields: Prisma.EmpresaFieldRefs
      operations: {
        findUnique: {
          args: Prisma.EmpresaFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmpresaPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.EmpresaFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmpresaPayload>
        }
        findFirst: {
          args: Prisma.EmpresaFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmpresaPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.EmpresaFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmpresaPayload>
        }
        findMany: {
          args: Prisma.EmpresaFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmpresaPayload>[]
        }
        create: {
          args: Prisma.EmpresaCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmpresaPayload>
        }
        createMany: {
          args: Prisma.EmpresaCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.EmpresaCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmpresaPayload>[]
        }
        delete: {
          args: Prisma.EmpresaDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmpresaPayload>
        }
        update: {
          args: Prisma.EmpresaUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmpresaPayload>
        }
        deleteMany: {
          args: Prisma.EmpresaDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.EmpresaUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.EmpresaUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmpresaPayload>[]
        }
        upsert: {
          args: Prisma.EmpresaUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmpresaPayload>
        }
        aggregate: {
          args: Prisma.EmpresaAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEmpresa>
        }
        groupBy: {
          args: Prisma.EmpresaGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EmpresaGroupByOutputType>[]
        }
        count: {
          args: Prisma.EmpresaCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EmpresaCountAggregateOutputType> | number
        }
      }
    }
    Departamento: {
      payload: Prisma.$DepartamentoPayload<ExtArgs>
      fields: Prisma.DepartamentoFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DepartamentoFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartamentoPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DepartamentoFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartamentoPayload>
        }
        findFirst: {
          args: Prisma.DepartamentoFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartamentoPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DepartamentoFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartamentoPayload>
        }
        findMany: {
          args: Prisma.DepartamentoFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartamentoPayload>[]
        }
        create: {
          args: Prisma.DepartamentoCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartamentoPayload>
        }
        createMany: {
          args: Prisma.DepartamentoCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DepartamentoCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartamentoPayload>[]
        }
        delete: {
          args: Prisma.DepartamentoDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartamentoPayload>
        }
        update: {
          args: Prisma.DepartamentoUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartamentoPayload>
        }
        deleteMany: {
          args: Prisma.DepartamentoDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DepartamentoUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DepartamentoUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartamentoPayload>[]
        }
        upsert: {
          args: Prisma.DepartamentoUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DepartamentoPayload>
        }
        aggregate: {
          args: Prisma.DepartamentoAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDepartamento>
        }
        groupBy: {
          args: Prisma.DepartamentoGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DepartamentoGroupByOutputType>[]
        }
        count: {
          args: Prisma.DepartamentoCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DepartamentoCountAggregateOutputType> | number
        }
      }
    }
    Bot: {
      payload: Prisma.$BotPayload<ExtArgs>
      fields: Prisma.BotFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BotFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BotFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotPayload>
        }
        findFirst: {
          args: Prisma.BotFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BotFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotPayload>
        }
        findMany: {
          args: Prisma.BotFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotPayload>[]
        }
        create: {
          args: Prisma.BotCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotPayload>
        }
        createMany: {
          args: Prisma.BotCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BotCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotPayload>[]
        }
        delete: {
          args: Prisma.BotDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotPayload>
        }
        update: {
          args: Prisma.BotUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotPayload>
        }
        deleteMany: {
          args: Prisma.BotDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BotUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BotUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotPayload>[]
        }
        upsert: {
          args: Prisma.BotUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotPayload>
        }
        aggregate: {
          args: Prisma.BotAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBot>
        }
        groupBy: {
          args: Prisma.BotGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BotGroupByOutputType>[]
        }
        count: {
          args: Prisma.BotCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BotCountAggregateOutputType> | number
        }
      }
    }
    BotAsset: {
      payload: Prisma.$BotAssetPayload<ExtArgs>
      fields: Prisma.BotAssetFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BotAssetFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotAssetPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BotAssetFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotAssetPayload>
        }
        findFirst: {
          args: Prisma.BotAssetFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotAssetPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BotAssetFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotAssetPayload>
        }
        findMany: {
          args: Prisma.BotAssetFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotAssetPayload>[]
        }
        create: {
          args: Prisma.BotAssetCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotAssetPayload>
        }
        createMany: {
          args: Prisma.BotAssetCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BotAssetCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotAssetPayload>[]
        }
        delete: {
          args: Prisma.BotAssetDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotAssetPayload>
        }
        update: {
          args: Prisma.BotAssetUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotAssetPayload>
        }
        deleteMany: {
          args: Prisma.BotAssetDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BotAssetUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BotAssetUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotAssetPayload>[]
        }
        upsert: {
          args: Prisma.BotAssetUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotAssetPayload>
        }
        aggregate: {
          args: Prisma.BotAssetAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBotAsset>
        }
        groupBy: {
          args: Prisma.BotAssetGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BotAssetGroupByOutputType>[]
        }
        count: {
          args: Prisma.BotAssetCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BotAssetCountAggregateOutputType> | number
        }
      }
    }
    BotEmpresa: {
      payload: Prisma.$BotEmpresaPayload<ExtArgs>
      fields: Prisma.BotEmpresaFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BotEmpresaFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotEmpresaPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BotEmpresaFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotEmpresaPayload>
        }
        findFirst: {
          args: Prisma.BotEmpresaFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotEmpresaPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BotEmpresaFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotEmpresaPayload>
        }
        findMany: {
          args: Prisma.BotEmpresaFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotEmpresaPayload>[]
        }
        create: {
          args: Prisma.BotEmpresaCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotEmpresaPayload>
        }
        createMany: {
          args: Prisma.BotEmpresaCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BotEmpresaCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotEmpresaPayload>[]
        }
        delete: {
          args: Prisma.BotEmpresaDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotEmpresaPayload>
        }
        update: {
          args: Prisma.BotEmpresaUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotEmpresaPayload>
        }
        deleteMany: {
          args: Prisma.BotEmpresaDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BotEmpresaUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BotEmpresaUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotEmpresaPayload>[]
        }
        upsert: {
          args: Prisma.BotEmpresaUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BotEmpresaPayload>
        }
        aggregate: {
          args: Prisma.BotEmpresaAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBotEmpresa>
        }
        groupBy: {
          args: Prisma.BotEmpresaGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BotEmpresaGroupByOutputType>[]
        }
        count: {
          args: Prisma.BotEmpresaCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BotEmpresaCountAggregateOutputType> | number
        }
      }
    }
    FolhaBot: {
      payload: Prisma.$FolhaBotPayload<ExtArgs>
      fields: Prisma.FolhaBotFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FolhaBotFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolhaBotPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FolhaBotFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolhaBotPayload>
        }
        findFirst: {
          args: Prisma.FolhaBotFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolhaBotPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FolhaBotFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolhaBotPayload>
        }
        findMany: {
          args: Prisma.FolhaBotFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolhaBotPayload>[]
        }
        create: {
          args: Prisma.FolhaBotCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolhaBotPayload>
        }
        createMany: {
          args: Prisma.FolhaBotCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.FolhaBotCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolhaBotPayload>[]
        }
        delete: {
          args: Prisma.FolhaBotDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolhaBotPayload>
        }
        update: {
          args: Prisma.FolhaBotUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolhaBotPayload>
        }
        deleteMany: {
          args: Prisma.FolhaBotDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FolhaBotUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.FolhaBotUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolhaBotPayload>[]
        }
        upsert: {
          args: Prisma.FolhaBotUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FolhaBotPayload>
        }
        aggregate: {
          args: Prisma.FolhaBotAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFolhaBot>
        }
        groupBy: {
          args: Prisma.FolhaBotGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FolhaBotGroupByOutputType>[]
        }
        count: {
          args: Prisma.FolhaBotCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FolhaBotCountAggregateOutputType> | number
        }
      }
    }
    Transacao: {
      payload: Prisma.$TransacaoPayload<ExtArgs>
      fields: Prisma.TransacaoFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TransacaoFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransacaoPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TransacaoFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransacaoPayload>
        }
        findFirst: {
          args: Prisma.TransacaoFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransacaoPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TransacaoFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransacaoPayload>
        }
        findMany: {
          args: Prisma.TransacaoFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransacaoPayload>[]
        }
        create: {
          args: Prisma.TransacaoCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransacaoPayload>
        }
        createMany: {
          args: Prisma.TransacaoCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TransacaoCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransacaoPayload>[]
        }
        delete: {
          args: Prisma.TransacaoDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransacaoPayload>
        }
        update: {
          args: Prisma.TransacaoUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransacaoPayload>
        }
        deleteMany: {
          args: Prisma.TransacaoDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TransacaoUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TransacaoUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransacaoPayload>[]
        }
        upsert: {
          args: Prisma.TransacaoUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TransacaoPayload>
        }
        aggregate: {
          args: Prisma.TransacaoAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTransacao>
        }
        groupBy: {
          args: Prisma.TransacaoGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TransacaoGroupByOutputType>[]
        }
        count: {
          args: Prisma.TransacaoCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TransacaoCountAggregateOutputType> | number
        }
      }
    }
    Arquivo: {
      payload: Prisma.$ArquivoPayload<ExtArgs>
      fields: Prisma.ArquivoFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ArquivoFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArquivoPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ArquivoFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArquivoPayload>
        }
        findFirst: {
          args: Prisma.ArquivoFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArquivoPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ArquivoFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArquivoPayload>
        }
        findMany: {
          args: Prisma.ArquivoFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArquivoPayload>[]
        }
        create: {
          args: Prisma.ArquivoCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArquivoPayload>
        }
        createMany: {
          args: Prisma.ArquivoCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ArquivoCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArquivoPayload>[]
        }
        delete: {
          args: Prisma.ArquivoDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArquivoPayload>
        }
        update: {
          args: Prisma.ArquivoUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArquivoPayload>
        }
        deleteMany: {
          args: Prisma.ArquivoDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ArquivoUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ArquivoUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArquivoPayload>[]
        }
        upsert: {
          args: Prisma.ArquivoUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ArquivoPayload>
        }
        aggregate: {
          args: Prisma.ArquivoAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateArquivo>
        }
        groupBy: {
          args: Prisma.ArquivoGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ArquivoGroupByOutputType>[]
        }
        count: {
          args: Prisma.ArquivoCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ArquivoCountAggregateOutputType> | number
        }
      }
    }
    Notificacao: {
      payload: Prisma.$NotificacaoPayload<ExtArgs>
      fields: Prisma.NotificacaoFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NotificacaoFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificacaoPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NotificacaoFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificacaoPayload>
        }
        findFirst: {
          args: Prisma.NotificacaoFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificacaoPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NotificacaoFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificacaoPayload>
        }
        findMany: {
          args: Prisma.NotificacaoFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificacaoPayload>[]
        }
        create: {
          args: Prisma.NotificacaoCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificacaoPayload>
        }
        createMany: {
          args: Prisma.NotificacaoCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NotificacaoCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificacaoPayload>[]
        }
        delete: {
          args: Prisma.NotificacaoDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificacaoPayload>
        }
        update: {
          args: Prisma.NotificacaoUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificacaoPayload>
        }
        deleteMany: {
          args: Prisma.NotificacaoDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NotificacaoUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NotificacaoUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificacaoPayload>[]
        }
        upsert: {
          args: Prisma.NotificacaoUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NotificacaoPayload>
        }
        aggregate: {
          args: Prisma.NotificacaoAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotificacao>
        }
        groupBy: {
          args: Prisma.NotificacaoGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificacaoGroupByOutputType>[]
        }
        count: {
          args: Prisma.NotificacaoCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificacaoCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UsuarioScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  email: 'email',
  palavraPasse: 'palavraPasse',
  image_path: 'image_path',
  role: 'role',
  estado_conta: 'estado_conta',
  created_at: 'created_at'
} as const

export type UsuarioScalarFieldEnum = (typeof UsuarioScalarFieldEnum)[keyof typeof UsuarioScalarFieldEnum]


export const EmpresaScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  sector: 'sector',
  website: 'website',
  logotipo: 'logotipo',
  cor_primaria: 'cor_primaria',
  created_at: 'created_at',
  usuarioId: 'usuarioId'
} as const

export type EmpresaScalarFieldEnum = (typeof EmpresaScalarFieldEnum)[keyof typeof EmpresaScalarFieldEnum]


export const DepartamentoScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  empresaId: 'empresaId'
} as const

export type DepartamentoScalarFieldEnum = (typeof DepartamentoScalarFieldEnum)[keyof typeof DepartamentoScalarFieldEnum]


export const BotScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  funcao: 'funcao',
  descricao: 'descricao',
  preco_mensal: 'preco_mensal',
  custo_api_est: 'custo_api_est',
  rating: 'rating',
  tags: 'tags'
} as const

export type BotScalarFieldEnum = (typeof BotScalarFieldEnum)[keyof typeof BotScalarFieldEnum]


export const BotAssetScalarFieldEnum = {
  id: 'id',
  botId: 'botId',
  estado: 'estado',
  video_path: 'video_path',
  file_size: 'file_size',
  mime_type: 'mime_type'
} as const

export type BotAssetScalarFieldEnum = (typeof BotAssetScalarFieldEnum)[keyof typeof BotAssetScalarFieldEnum]


export const BotEmpresaScalarFieldEnum = {
  id: 'id',
  botId: 'botId',
  empresaId: 'empresaId',
  departamentoId: 'departamentoId',
  data_contrato: 'data_contrato',
  status: 'status'
} as const

export type BotEmpresaScalarFieldEnum = (typeof BotEmpresaScalarFieldEnum)[keyof typeof BotEmpresaScalarFieldEnum]


export const FolhaBotScalarFieldEnum = {
  id: 'id',
  botEmpresaId: 'botEmpresaId',
  mes: 'mes',
  ano: 'ano',
  custo_api_real: 'custo_api_real',
  valor_cobrado: 'valor_cobrado',
  horas_uso: 'horas_uso'
} as const

export type FolhaBotScalarFieldEnum = (typeof FolhaBotScalarFieldEnum)[keyof typeof FolhaBotScalarFieldEnum]


export const TransacaoScalarFieldEnum = {
  id: 'id',
  empresaId: 'empresaId',
  valor: 'valor',
  metodo: 'metodo',
  status: 'status',
  referencia: 'referencia',
  created_at: 'created_at'
} as const

export type TransacaoScalarFieldEnum = (typeof TransacaoScalarFieldEnum)[keyof typeof TransacaoScalarFieldEnum]


export const ArquivoScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  tipo: 'tipo',
  url: 'url',
  empresaId: 'empresaId',
  created_at: 'created_at'
} as const

export type ArquivoScalarFieldEnum = (typeof ArquivoScalarFieldEnum)[keyof typeof ArquivoScalarFieldEnum]


export const NotificacaoScalarFieldEnum = {
  id: 'id',
  content: 'content',
  visualizada: 'visualizada',
  created_at: 'created_at',
  usuarioId: 'usuarioId'
} as const

export type NotificacaoScalarFieldEnum = (typeof NotificacaoScalarFieldEnum)[keyof typeof NotificacaoScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'Role'
 */
export type EnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role'>
    


/**
 * Reference to a field of type 'Role[]'
 */
export type ListEnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role[]'>
    


/**
 * Reference to a field of type 'ACCOUNT_STATUS'
 */
export type EnumACCOUNT_STATUSFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ACCOUNT_STATUS'>
    


/**
 * Reference to a field of type 'ACCOUNT_STATUS[]'
 */
export type ListEnumACCOUNT_STATUSFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ACCOUNT_STATUS[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Decimal'
 */
export type DecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal'>
    


/**
 * Reference to a field of type 'Decimal[]'
 */
export type ListDecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    


/**
 * Reference to a field of type 'BOT_STATE'
 */
export type EnumBOT_STATEFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BOT_STATE'>
    


/**
 * Reference to a field of type 'BOT_STATE[]'
 */
export type ListEnumBOT_STATEFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BOT_STATE[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'TRANSACTION_STATUS'
 */
export type EnumTRANSACTION_STATUSFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TRANSACTION_STATUS'>
    


/**
 * Reference to a field of type 'TRANSACTION_STATUS[]'
 */
export type ListEnumTRANSACTION_STATUSFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TRANSACTION_STATUS[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}


export type Datasource = {
  url?: string
}
export type Datasources = {
  db?: Datasource
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export interface PrismaClientOptions {
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasources?: Datasources
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasourceUrl?: string
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging#the-log-option).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-planetscale`
   */
  adapter?: runtime.SqlDriverAdapterFactory | null
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
}
export type GlobalOmitConfig = {
  usuario?: Prisma.UsuarioOmit
  empresa?: Prisma.EmpresaOmit
  departamento?: Prisma.DepartamentoOmit
  bot?: Prisma.BotOmit
  botAsset?: Prisma.BotAssetOmit
  botEmpresa?: Prisma.BotEmpresaOmit
  folhaBot?: Prisma.FolhaBotOmit
  transacao?: Prisma.TransacaoOmit
  arquivo?: Prisma.ArquivoOmit
  notificacao?: Prisma.NotificacaoOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

