
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  Usuario: 'Usuario',
  Empresa: 'Empresa',
  Departamento: 'Departamento',
  Bot: 'Bot',
  BotAsset: 'BotAsset',
  BotEmpresa: 'BotEmpresa',
  FolhaBot: 'FolhaBot',
  Transacao: 'Transacao',
  Arquivo: 'Arquivo',
  Notificacao: 'Notificacao'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UsuarioScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  email: 'email',
  palavraPasse: 'palavraPasse',
  image_path: 'image_path',
  role: 'role',
  estado_conta: 'estado_conta',
  created_at: 'created_at'
} as const

export type UsuarioScalarFieldEnum = (typeof UsuarioScalarFieldEnum)[keyof typeof UsuarioScalarFieldEnum]


export const EmpresaScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  sector: 'sector',
  website: 'website',
  logotipo: 'logotipo',
  cor_primaria: 'cor_primaria',
  created_at: 'created_at',
  usuarioId: 'usuarioId'
} as const

export type EmpresaScalarFieldEnum = (typeof EmpresaScalarFieldEnum)[keyof typeof EmpresaScalarFieldEnum]


export const DepartamentoScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  empresaId: 'empresaId'
} as const

export type DepartamentoScalarFieldEnum = (typeof DepartamentoScalarFieldEnum)[keyof typeof DepartamentoScalarFieldEnum]


export const BotScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  funcao: 'funcao',
  descricao: 'descricao',
  preco_mensal: 'preco_mensal',
  custo_api_est: 'custo_api_est',
  rating: 'rating',
  tags: 'tags'
} as const

export type BotScalarFieldEnum = (typeof BotScalarFieldEnum)[keyof typeof BotScalarFieldEnum]


export const BotAssetScalarFieldEnum = {
  id: 'id',
  botId: 'botId',
  estado: 'estado',
  video_path: 'video_path',
  file_size: 'file_size',
  mime_type: 'mime_type'
} as const

export type BotAssetScalarFieldEnum = (typeof BotAssetScalarFieldEnum)[keyof typeof BotAssetScalarFieldEnum]


export const BotEmpresaScalarFieldEnum = {
  id: 'id',
  botId: 'botId',
  empresaId: 'empresaId',
  departamentoId: 'departamentoId',
  data_contrato: 'data_contrato',
  status: 'status'
} as const

export type BotEmpresaScalarFieldEnum = (typeof BotEmpresaScalarFieldEnum)[keyof typeof BotEmpresaScalarFieldEnum]


export const FolhaBotScalarFieldEnum = {
  id: 'id',
  botEmpresaId: 'botEmpresaId',
  mes: 'mes',
  ano: 'ano',
  custo_api_real: 'custo_api_real',
  valor_cobrado: 'valor_cobrado',
  horas_uso: 'horas_uso'
} as const

export type FolhaBotScalarFieldEnum = (typeof FolhaBotScalarFieldEnum)[keyof typeof FolhaBotScalarFieldEnum]


export const TransacaoScalarFieldEnum = {
  id: 'id',
  empresaId: 'empresaId',
  valor: 'valor',
  metodo: 'metodo',
  status: 'status',
  referencia: 'referencia',
  created_at: 'created_at'
} as const

export type TransacaoScalarFieldEnum = (typeof TransacaoScalarFieldEnum)[keyof typeof TransacaoScalarFieldEnum]


export const ArquivoScalarFieldEnum = {
  id: 'id',
  nome: 'nome',
  tipo: 'tipo',
  url: 'url',
  empresaId: 'empresaId',
  created_at: 'created_at'
} as const

export type ArquivoScalarFieldEnum = (typeof ArquivoScalarFieldEnum)[keyof typeof ArquivoScalarFieldEnum]


export const NotificacaoScalarFieldEnum = {
  id: 'id',
  content: 'content',
  visualizada: 'visualizada',
  created_at: 'created_at',
  usuarioId: 'usuarioId'
} as const

export type NotificacaoScalarFieldEnum = (typeof NotificacaoScalarFieldEnum)[keyof typeof NotificacaoScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

