
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Usuario
 * 
 */
export type Usuario = Prisma.UsuarioModel
/**
 * Model Empresa
 * 
 */
export type Empresa = Prisma.EmpresaModel
/**
 * Model Departamento
 * 
 */
export type Departamento = Prisma.DepartamentoModel
/**
 * Model Bot
 * 
 */
export type Bot = Prisma.BotModel
/**
 * Model BotAsset
 * 
 */
export type BotAsset = Prisma.BotAssetModel
/**
 * Model BotEmpresa
 * 
 */
export type BotEmpresa = Prisma.BotEmpresaModel
/**
 * Model FolhaBot
 * 
 */
export type FolhaBot = Prisma.FolhaBotModel
/**
 * Model Transacao
 * 
 */
export type Transacao = Prisma.TransacaoModel
/**
 * Model Arquivo
 * 
 */
export type Arquivo = Prisma.ArquivoModel
/**
 * Model Notificacao
 * 
 */
export type Notificacao = Prisma.NotificacaoModel
