
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 * 
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'

import * as runtime from "@prisma/client/runtime/library"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Usuarios
 * const usuarios = await prisma.usuario.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname)
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }


// file annotations for bundling tools to include these files
path.join(__dirname, "query_engine-windows.dll.node")
path.join(process.cwd(), "prisma/prisma/query_engine-windows.dll.node")

/**
 * Model Usuario
 * 
 */
export type Usuario = Prisma.UsuarioModel
/**
 * Model Empresa
 * 
 */
export type Empresa = Prisma.EmpresaModel
/**
 * Model Departamento
 * 
 */
export type Departamento = Prisma.DepartamentoModel
/**
 * Model Bot
 * 
 */
export type Bot = Prisma.BotModel
/**
 * Model BotAsset
 * 
 */
export type BotAsset = Prisma.BotAssetModel
/**
 * Model BotEmpresa
 * 
 */
export type BotEmpresa = Prisma.BotEmpresaModel
/**
 * Model FolhaBot
 * 
 */
export type FolhaBot = Prisma.FolhaBotModel
/**
 * Model Transacao
 * 
 */
export type Transacao = Prisma.TransacaoModel
/**
 * Model Arquivo
 * 
 */
export type Arquivo = Prisma.ArquivoModel
/**
 * Model Notificacao
 * 
 */
export type Notificacao = Prisma.NotificacaoModel
