
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  ADMIN: 'ADMIN',
  GESTOR: 'GESTOR'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const ACCOUNT_STATUS = {
  ACTIVA: 'ACTIVA',
  DESATIVADA: 'DESATIVADA',
  PENDENTE: 'PENDENTE',
  SUSPENSA: 'SUSPENSA'
} as const

export type ACCOUNT_STATUS = (typeof ACCOUNT_STATUS)[keyof typeof ACCOUNT_STATUS]


export const TRANSACTION_STATUS = {
  PENDENTE: 'PENDENTE',
  APROVADO: 'APROVADO',
  REJEITADO: 'REJEITADO',
  CANCELADO: 'CANCELADO'
} as const

export type TRANSACTION_STATUS = (typeof TRANSACTION_STATUS)[keyof typeof TRANSACTION_STATUS]


export const BOT_STATE = {
  APRESENTACAO: 'APRESENTACAO',
  TRABALHANDO: 'TRABALHANDO',
  REPOUSANDO: 'REPOUSANDO',
  CONVERSANDO: 'CONVERSANDO',
  RELAXANDO: 'RELAXANDO'
} as const

export type BOT_STATE = (typeof BOT_STATE)[keyof typeof BOT_STATE]
