
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Usuario'
export type * from './models/Empresa'
export type * from './models/Departamento'
export type * from './models/Bot'
export type * from './models/BotAsset'
export type * from './models/BotEmpresa'
export type * from './models/FolhaBot'
export type * from './models/Transacao'
export type * from './models/Arquivo'
export type * from './models/Notificacao'
export type * from './commonInputTypes'